### ISSUE TITLE
Scarab Executable Doesn't Properly Close

### ISSUE THREAD

**Issue by dastrdly6585** [fifty-six/Scarab#100]
### Scarab Version

v1.17.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Open Scarab and then hit the "x" button to close the Scarab window.

### Expected Behaviour

Scarab executable shuts down and releases its memory.

### Actual Behaviour

Scarab executable remains as a background process with memory use stuck at the shutdown amount and does not go away unless manually terminated (e.g. using "End Task" in Task Manager)

### Logs

Full log: 
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/9195202/ModInstaller.log)

Log of one session where program opened and immediately closed: 
[5cdd055c-a322-4e67-86c9-3699180a5a3eModInstaller.log](https://github.com/fifty-six/Scarab/files/9195209/5cdd055c-a322-4e67-86c9-3699180a5a3eModInstaller.log)

Screenshot of Task Manager background processes: 
![Scarab_BG_Processes_Task_Manager](https://user-images.githubusercontent.com/13990010/181166800-2412723a-f82c-4cc9-b98e-ae2f725f031d.jpg)

**Comment by fifty-six** [comment]
Thanks for the report.
