### ISSUE TITLE
fall through floor

### ISSUE THREAD

**Issue by slimewhal** [fifty-six/Scarab#101]
### Scarab Version

1.19

### Hollow Knight Version

1.5.78.1833

### Steps to Reproduce

I just opened a save and I fall through the floor

### Expected Behaviour

not fall through the floor

### Actual Behaviour

I fell through the floor, I can't figure out how to fix it. I tried no clip and fly back up but it wouldn't work

### Logs

none

**Comment by fifty-six** [comment]
This is likely just a bug in one of your mods, which you should report to whatever mod is causing it. If you disable your mods does it work fine?
