### ISSUE TITLE
Cannot open Scarab MacOS 13.0

### ISSUE THREAD

**Issue by TodTheSushiMonster** [fifty-six/Scarab#105]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

I am on the macOS beta for venture (13.0), and it isn't letting me launch it, whenever I try and open it it says 

"“Scarab” cannot be opened because the developer cannot be verified. 
macOS cannot verify that this app is free from malware"
(Screenshot attached)

<img width="265" alt="image" src="https://user-images.githubusercontent.com/69654470/187034646-fc3acfc2-6e1a-4d17-878e-095102a38e42.png">

### Expected Behaviour

The app to open

### Actual Behaviour

It asked me to move it to the trash, like it says above

### Logs

None

**Comment by TodTheSushiMonster** [comment]
right clicking and opening it that way worked, thank you!

**Comment by Aces-and-Jacks** [comment]
no problem glad I can help

**Comment by Aces-and-Jacks** [comment]
tho if you figured it out it is probably a good idea to close the issue/bug thingy
