### ISSUE TITLE
I can't download Scarab for MacOs

### ISSUE THREAD

**Issue by LukeSkywalker914** [fifty-six/Scarab#106]
### Scarab Version

cant download

### Hollow Knight Version

just got the game

### Steps to Reproduce

I am running on a Mac Mini. When i try to download the macos.zip file to get Scarab it downloads but then tells me it cannot open because it is not verified and "may contain malware"
![Screen Shot 2022-08-27 at 8 33 24 PM](https://user-images.githubusercontent.com/112297532/187056185-f27aafa0-5682-43d9-b787-ae7a189f4c86.png)
.

### Expected Behaviour

for it to open the application without problems

### Actual Behaviour

it gave me the error messag
![Screen Shot 2022-08-27 at 8 33 24 PM](https://user-images.githubusercontent.com/112297532/187056198-bd1e1d48-dd2f-4e2d-ab2d-cef363c94c06.png)
e

### Logs

???

**Comment by fifty-six** [comment]
Right click -> Open
