### ISSUE TITLE
Invalid Hollow Knight folder on GOG

### ISSUE THREAD

**Issue by Dastan21** [fifty-six/Scarab#11]
Scarab doesn't accept Hollow Knight's folder if it is installed from GOG

**Comment by fifty-six** [comment]
Are you on Windows? I have a copy of the game on GoG and it seems to work fine for me. You need to select the "Hollow Knight" folder containing "Hollow Knight_Data".

**Comment by Dastan21** [comment]
Ok I've fixed it, the folder contained 2 Hollow_Knight_Data folders.
