### ISSUE TITLE
Breaks Steam Deck controller integration

### ISSUE THREAD

**Issue by i32ropie** [fifty-six/Scarab#113]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Simply install Scarab in Steam Deck after having Hollow Knight installed

### Expected Behaviour

The game should work with the Steam Deck controller

### Actual Behaviour

After using Scarab, the game won't recognise the Steam Deck controller and you won't be able to play

### Logs

None

**Comment by fifty-six** [comment]
Disable native controls in-game and restart the game (you can do this with the touch screen).

**Comment by i32ropie** [comment]
Works, thanks :)
