### ISSUE TITLE
Error while installing a mod

### ISSUE THREAD

**Issue by Pat4962** [fifty-six/Scarab#114]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

download scarab on a new laptop and attempt to install any mod

### Expected Behaviour

Aforementioned mod to install

### Actual Behaviour

It did not install and gave me an error stating
An exception occured while installing or uninstalling [mod name]

### Logs

⠀

**Comment by fifty-six** [comment]
This is unactionable without logs. Can you provide the logs?

**Comment by Tsunae** [comment]
I have the same problem. Where can I get the logs?
