### ISSUE TITLE
it wont let me open scarab linux

### ISSUE THREAD

**Issue by AKIRA77333** [fifty-six/Scarab#123]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

v1.4.3.2

### Steps to Reproduce

don't know

### Expected Behaviour

I thought I could run it normally but I have no idea how to do it

### Actual Behaviour

I downloaded and extracted the linux.zip but when I run it it keeps loading and nothing opens, I don't know which application to use to run it or if I have to do it from the linux terminal

### Logs

none

**Comment by Ordoviz** [comment]
Scarab only supports Hollow Knight 1.5 (not sure if this is related to your issue, though).

**Comment by fifty-six** [comment]
What Ordoviz said is correct, yeah. If you don't have a 1.5 copy then there's no point in using Scarab at all, if you do feel free to lmk and I'll reopen the issue. The logs would be at `~/.config/HKModInstaller/` anyways though fwiw.
