### ISSUE TITLE
Feature request: add mod "profiles"

### ISSUE THREAD

**Issue by thislooksfun** [fifty-six/Scarab#130]
Again, not a bug, but this was the only way I could file this.

I find myself often switching between multiple sets of mods (one for mostly vanilla play, one for randomizers, etc), and I keep having to manually turn the mods off and on again to get the sets I want. It would be really nice if there was a way to save a set of enabled mods so I could apply just that set with a single button.

**Comment by fifty-six** [comment]
Duplicate of #42. Half the point of the filing system was me not having the motivation or time for feature requests but there's not really a point if everybody is just gonna make bug reports full of `a` and edit it I guess.
