### ISSUE TITLE
I can't open the .exe file.

### ISSUE THREAD

**Issue by Efexacore** [fifty-six/Scarab#132]
### Scarab Version

v1.20.0.0

### Hollow Knight Version

v1.5.78.11388

### Steps to Reproduce

It may try to run the .exe file.

### Expected Behaviour

Error-free opening of the .exe file.

### Actual Behaviour

It gives the error "Scarab has stopped working".

### Logs

Launching...
Launching...
Launching...
Launching...
Launching...

**Comment by fifty-six** [comment]
It's extracted and all, right?

**Comment by Efexacore** [comment]
> It's extracted and all, right?


Yes, i extracted all the files.

**Comment by fifty-six** [comment]
What was it? Sorry I couldn't help more btw - just not entirely sure where to even start debugging that
