### ISSUE TITLE
Scarab crashes on loading due to font issues

### ISSUE THREAD

**Issue by Link459** [fifty-six/Scarab#137]
### Scarab Version

v1.20.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

I do not know why it happens

### Expected Behaviour

to launch normally

### Actual Behaviour

it opened showed a grey screen and then crashed. I am on arch linux. Everything is up to date. using i3 as wm if that matters. font path is not modified in any way. default font is FreeSans

### Logs

[ModInstaller.log](https://github.com/fifty-six/Scarab/files/10735808/ModInstaller.log)

**Comment by fifty-six** [comment]
Try getting [ttf-ms-fonts](https://aur.archlinux.org/packages/ttf-ms-fonts), if that doesn't work try running it with `LC_ALL=C ./Scarab`

**Comment by Cavernosa** [comment]
I get the same error when launching with `LANG=ja_JP.utf8 ./Scarab` both in 1.19 and 1.20.
ttf-ms-fonts didn't work

**Comment by fifty-six** [comment]
use `LC_ALL=C` not `LANG=ja_JP.utf8`, it's an issue with different default locales
