### ISSUE TITLE
file not found issue

### ISSUE THREAD

**Issue by baggetss** [fifty-six/Scarab#138]
### Scarab Version

v1.20.0.0

### Hollow Knight Version

unsure

### Steps to Reproduce

i am unsure i reinstalled scarab and hollow knight i also tried all of the files i could inside hollow knight, please tell me how to fix this

### Expected Behaviour

for the issue to be fixed after reinstall

### Actual Behaviour

the issue persisted

### Logs

none

**Comment by fifty-six** [comment]
I need logs to do anything regarding this. They're in `%appdata%\HKModInstaller`

**Comment by CrazyNerd1** [comment]
Got it to work now, think it just took steam a few tries to verify one of the dll files. Here's the logs anyway if you wanted them. Cheers
________________________________

**Comment by fifty-six** [comment]
Ah ok, great! Though I don't think logs attached from the email reply lmao

**Comment by catjo19** [comment]
do I need to have installed hollow knight on steam for it to find my hollow knight file? I installed on the xbox store on windows.

**Comment by fifty-six** [comment]
That's an unrelated issue, you just have to select your installation path manually.
