### ISSUE TITLE
No executable file

### ISSUE THREAD

**Issue by nousernameavailabl33** [fifty-six/Scarab#139]
### Scarab Version

Scarab version: I do not know

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Linux mint downloaded scarab and no executable on extracting of linux.zip

### Expected Behaviour

to there be an executable file to use on linux

### Actual Behaviour

there was only libharfbusssharp.so libskiasharp.so Scarab (not an executable) and Scarab.pdb

### Logs

None

**Comment by fifty-six** [comment]
```sh
% ls
Scarab  Scarab.pdb  libHarfBuzzSharp.so  libSkiaSharp.so
% ls -la
total 101772
drwx------ 1 home network      100 Mar  3 19:23 .
drwxr-xr-x 1 home network     1670 Mar  3 19:23 ..
-rwxr-xr-x 1 home network 93710799 Jan 29 20:03 Scarab
-rw-r--r-- 1 home network    41332 Jan 29 20:03 Scarab.pdb
-rw-r--r-- 1 home network  1574248 Jan 29 20:03 libHarfBuzzSharp.so
-rw-r--r-- 1 home network  8876256 Jan 29 20:03 libSkiaSharp.so
%                                                                                                 ~/Downloads/linux
```
It has the executable bit set, so you should just be able to run it. Are you sure it's not executable for you?

**Comment by nousernameavailabl33** [comment]
(I'm really bad at this I just want to mod hollowknight) so from what I understand you're talking about the Scarab file.
I can execute it but only with archive manager, and it says file type not supported, If you're talking about Scarab.pdb I can open it with libreofficewriter and it says "BSJB########"

**Comment by fifty-six** [comment]
Could you show me a picture? Can you try going from the terminal and running it there?

**Comment by nousernameavailabl33** [comment]
okay,
![permissiondenied](https://user-images.githubusercontent.com/111671194/222940256-b2e02015-b744-43eb-afef-a530ddd913eb.png) this is what happens when I try the terminal. and
![scarabfail](https://user-images.githubusercontent.com/111671194/222940279-3b88e93a-ab6b-425a-8bdf-d09b7a12a660.png)
this is what happens with libreoffice writer.

**Comment by fifty-six** [comment]
Don't execute the pdb, it's the file *without* an extension.

**Comment by nousernameavailabl33** [comment]
what is an extension? (sorry as I mentioned Im pretty bad at this)

**Comment by nousernameavailabl33** [comment]
ah okay

**Comment by nousernameavailabl33** [comment]
Thank you so much, I got it working!
