### ISSUE TITLE
An exception occurred while installing or uninstalling

### ISSUE THREAD

**Issue by shadowibm** [fifty-six/Scarab#142]
### Scarab Version

v1.31.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

When tried to download a mod, shows "An exception occurred while installing or uninstalling X", then Hollow Knight stops working and I need to verify the game integrity for it to work again.
![imagen_2023-03-23_131620648](https://user-images.githubusercontent.com/40765409/227201078-73e5a0fe-376d-4b4c-8953-ac394facdbac.png)

### Expected Behaviour

I downloaded Scarab normally so I was hoping for it to work properly.

### Actual Behaviour

It wont let me download mods and it breaks the game.

### Logs

[ModInstaller.log](https://github.com/fifty-six/Scarab/files/11050677/ModInstaller.log)
![image](https://user-images.githubusercontent.com/40765409/227202207-d09a7441-4437-445d-8ca3-e06951c2c529.png)

**Comment by Lyenus** [comment]
Try running it in admin mode. I had the same issue and admin mode fixed it.

**Comment by shadowibm** [comment]
Doesn't works for me

**Comment by fifty-six** [comment]
Could you try deleting 'Assembly-CSharp.dll.v'?

**Comment by shadowibm** [comment]
It creates it again when I click on Install on any mod, and the error persists

**Comment by fifty-six** [comment]
Could I have the log after that?

**Comment by shadowibm** [comment]
Sure
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/11100553/ModInstaller.log)

**Comment by shadowibm** [comment]
Done! It worked, thank you so much Ive been trying things since like for 5 days
