### ISSUE TITLE
Scarab Can't Find hollow_knight_Data even when I select it.

### ISSUE THREAD

**Issue by Nardeem** [fifty-six/Scarab#149]
### Scarab Version

v1.31.0.0 Windows

### Hollow Knight Version

1.4.2.4

### Steps to Reproduce

I'm not sure what did it. This is basically the same as SlaysikGG's "scarab cant find hollow_knight_Data or exception occurred while installing or uninstalling #96" one except I don't have Assembly-CSharp.dll or UnityEngine.dll in the managed folder.

### Expected Behaviour

I expected it'd just figure "oh that's it" and let me download and install mods or whatever crap you do

### Actual Behaviour

It just kept acting as if it is brain dead and kept saying it's not it.

### Logs

None

**Comment by fifty-six** [comment]
1) The installer doesn't support 1.4.2.4 - why are you even using it?
2) A Managed folder without both of those dlls will not even run the game

**Comment by Nardeem** [comment]
But it runs just fine, also so I just move the save file to an updated version?
