### ISSUE TITLE
Auto-detection for installed mods

### ISSUE THREAD

**Issue by Jing-Linux** [fifty-six/Scarab#15]
It is really annoying when you have the mod installed but it doesn't show up in the Mod Installer. I hope you can fix this soon.

**Comment by mandar1jn** [comment]
Every installed mod should show up in the mod installer. Except for when you installed it manually. And in that case why should it show up?

**Comment by Jing-Linux** [comment]
Not when I switch the install location, For example, when I have two OS on my PC. It doesn't detect any of the installed mods in another installation on the other OS, even though I just installed them through Mod Installer on another OS.
And yeah, please don't ask why I have two OS nor why I want them both to be modded.

**Comment by fifty-six** [comment]
The issue with autodetection is that you have to handle versioning properly as well as deal with mods that aren't necessarily in the modlinks. I don't plan on adding it as a result of this, especially with most uses being edge cases like this one. You can alleviate your issue by just symlinking the json on Linux to the Windows one. Something like `ln -s ~/AppData/Roaming/HKModInstaller/InstalledMods.json ~/.config/HKModInstaller/InstalledMods.json`.
