### ISSUE TITLE
(Suggestion) Implement a better method for reliably getting game folder locations on Windows

### ISSUE THREAD

**Issue by Geroyuni** [fifty-six/Scarab#16]
I've found a [stackoverflow post](https://stackoverflow.com/questions/34090258/find-steam-games-folder/34091380#34091380) that details how to get the Steam library folders on Windows regardless of where they are in the system. This would reduce the amount of people that have to manually find the folder on their own, where Scarab would otherwise ask the user to manually find the folder, given right now it only searches for some hardcoded locations.

I've also searched about how this is on GoG, and it seems to be also saved to the registry, except GoG has an ID for each game right there. I think it'd be `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\GOG.com\Games\1308320804` (or `SOFTWARE\GOG.com` for 32-bit), in which the `path` string outputs the game folder.

Not sure if you're willing to go through the effort, but I thought I'd at least share what I found.

**Comment by fifty-six** [comment]
Yeah that sounds nice. I'll take a look at it when I get the chance

**Comment by fifty-six** [comment]
Thanks for the suggestion!
