### ISSUE TITLE
Can't change the language

### ISSUE THREAD

**Issue by Henonnnn** [fifty-six/Scarab#162]
### Scarab Version

v1.32.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Open scarab

### Expected Behaviour

It's not really a bug but that would be cool to have the ability to change the language cause even if I'm french I really prefer to have my scarab in english

### Actual Behaviour

I can't change the language and also the translation for "Out of date" in french is not really "Périmé" in this context it's more like "Dépassé"

### Logs

None

**Comment by fifty-six** [comment]
That makes sense, I'll add an option by next release - other people have said similar things about their own locales. I'll also change that translation

**Comment by fifty-six** [comment]
Just wanted to note I have started on this, it wasn't in this release as it's gotten tied up with some other changes, but I haven't forgotten about it or anything

**Comment by fifty-six** [comment]
https://github.com/fifty-six/Scarab/assets/10470872/f7cfc327-c7c0-4e6a-a091-d81b0c82cb95

:)
