### ISSUE TITLE
Latest update of Scarab closes immediately upon opening 

### ISSUE THREAD

**Issue by thistle-webinar** [fifty-six/Scarab#163]
### Scarab Version

v1.32.0.0

### Hollow Knight Version

v1.5.78.11833 

### Steps to Reproduce

1 -> have windows 11

2 -> download zip of latest update of Scarab

3 -> unzip file

4 -> open Scarab application

After step 4 Scarab immediately closes. Issue is resolved when using the previous version so it is likely a bug and not user error causing my problem. 

### Expected Behaviour

Scarab stays open when opened.

### Actual Behaviour

Scarab closes after being open.

### Logs

None

**Comment by fifty-six** [comment]
Are there no logs in `%appdata%\HKModInstaller`?
