### ISSUE TITLE
Mods stuck downloading forever

### ISSUE THREAD

**Issue by DragonLord867** [fifty-six/Scarab#167]
### Scarab Version

v1.33.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

It started with me downloading Hallownest Vocalized on an out of date version of Scarab while Hollow knight was still re-downloading off of Steam. This made it so when I Launched the game when both were finished installing, I was unable to interact with the menu. I manually stopped the game using Steam, then downloaded the latest release of Scarab and uninstalled Hallownest Vocalized. The game now functioned normally, but this glitch with scarab appeared.

### Expected Behaviour

Ability to download new mods.

### Actual Behaviour

I can no longer download mods using scarab. When I do it gets stuck in the loading animation (for lack of the actual word I'm looking for appearing in my head), never actually showing me a loading bar. I tried re-downloading scarab, and, thinking it might have been running into an issue with the firewall, made sure the firewall allowed the application through. Still nothing. Mods I already have installed still function. I tried uninstalling and reinstalling a mod I wasn't currently using, and it wont let me do that either. Weirdly enough, the one mod I've been able to install successfully is the Hallownest Vocalized Audio Loader dependency.
<img width="505" alt="Screenshot 2023-06-28 063525" src="https://github.com/fifty-six/Scarab/assets/138019996/d0c33ce2-faee-40ab-9067-f04cb5861960">

### Logs

None

**Comment by fifty-six** [comment]
Just to double check, could you try with like QoL? Hallownest Vocalized is super large so the lack of progress looks a bit like nothing happening. If nothing still happens, could you get the log from `%appdata%\HKModInstaller`?

**Comment by DragonLord867** [comment]
i think you might be right about the size thing, as my pc is already low on storage and it actually did work when I widened the mods i started trying to download. Thx a ton.

**Comment by DragonLord867** [comment]
this comment is just to close the issue
