### ISSUE TITLE
Scarab says that path to game files is invalid when the files are on the second disk.

### ISSUE THREAD

**Issue by asgilliard** [fifty-six/Scarab#169]
### Scarab Version

v1.33.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Move your game files to the second disk and then try to enter the game path.

### Expected Behaviour

I think, that programm must correctly install the game path whenever you enter it manually or/and your game files are not on the main disk.

### Actual Behaviour

My game files are on the second disk, not the disk C://, and when I want to enter path, I choose the correct folder, but Scarab says, that game path is invalid. 

### Logs

Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #48616240)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #34892981)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #45601378)

**Comment by HeavnWolf** [comment]
I have the same issue on Linux.
I reinstalled the game, changed the game directory to another disk, deleted the HKModInstaller folder in the .conf folder in the user folder (~/.conf/HKModInstaller).
It still doesn't work and I get the same errors in the .log file
```
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #65737292)
```

**Comment by HeavnWolf** [comment]
I've found a workaround on Linux.
In the configuration folder (~/.conf/HKModInstaller/), add a file called "HKInstallerSettings.json" and paste the following configuration in the file by editing the path of managed folder : 
```
{"ManagedFolder":"[YOUR_PATH]","AutoRemoveDeps":false}
```
Like this : 
```
{"ManagedFolder":"/mnt/sda1/SteamLibrary/steamapps/common/Hollow Knight/hollow_knight_Data/Managed","AutoRemoveDeps":false}
```
On Windows, I don't know if this will work, but you could try creating this file in the same folder where the log files are generated.

**Comment by fifty-six** [comment]
Could you try the artifacts from [this run](https://github.com/fifty-six/Scarab/actions/runs/5429011499)?

**Comment by asgilliard** [comment]
> On Windows, I don't know if this will work, but you could try creating this file in the same folder where the log files are generated.

I tried it few minutes ago. The file was already exist, and the path was in it, but there were "\\" between the folders. And it was "\\\\" after the disc letter. I replaced all this strange simbols and Scarab now works correctly.

**Comment by asgilliard** [comment]
> Could you try the artifacts from [this run](https://github.com/fifty-six/Scarab/actions/runs/5429011499)?

This fix works correctly, thank you.

**Comment by Clayton-lima** [comment]
Sorry, could i have a easier explanation of the solution ? apparently I'm having the same problem on windows

**Comment by Clayton-lima** [comment]
is there a easier explanation for that solution i think I'm having the same problem on windows.

or maybe i have to open a new issue ?

here's the log

Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #52136226)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #66572856)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #62284798)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #45028263)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #2601186)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #23410681)

**Comment by HeavnWolf** [comment]
> Could you try the artifacts from [this run](https://github.com/fifty-six/Scarab/actions/runs/5429011499)? 

I can confirm it works on Linux too, thank you!

**Comment by Chesare22** [comment]
> Could you try the artifacts from [this run](https://github.com/fifty-six/Scarab/actions/runs/5429011499)?

The artifacts have expired :/
