### ISSUE TITLE
An exception occurs when trying to install any mod.

### ISSUE THREAD

**Issue by BlueRedShark** [fifty-six/Scarab#171]
### Scarab Version

v1.33.0

### Hollow Knight Version

v1.5.80.11835

### Steps to Reproduce

Download Scarab and try to download any mod.

### Expected Behaviour

To download the mod

### Actual Behaviour

It doesn't  download
<img width="760" alt="Screenshot 2023-07-03 110024" src="https://github.com/fifty-six/Scarab/assets/126373228/704ad477-2333-4eaa-a411-11310eaceecc">

### Logs
[ModInstaller_Error_23-07-02 21-18-51.log](https://github.com/fifty-six/Scarab/files/11934664/ModInstaller_Error_23-07-02.21-18-51.log)

**Comment by fifty-six** [comment]
Why do you have `Y` in the logs slot? I'd need to see the logs to troubleshoot this, which you can get in `%appdata%\HKModInstaller`

**Comment by BlueRedShark** [comment]
> Why do you have `Y` in the logs slot? I'd need to see the logs to troubleshoot this, which you can get in `%appdata%\HKModInstaller`

Sorry, I didn't really know what to put.

**Comment by BlueRedShark** [comment]
> Why do you have `Y` in the logs slot? I'd need to see the logs to troubleshoot this, which you can get in `%appdata%\HKModInstaller`

I just got this log by trying again if it helps
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/11935778/ModInstaller.log)
