### ISSUE TITLE
Scarab cannot find the Managed folder or Assembly-CSharp on macos

### ISSUE THREAD

**Issue by teddy171** [fifty-six/Scarab#172]
### Scarab Version

v1.33.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

On macos, when scarab is opened and it report ```Missing Managed folder or Assembly-CSharp!```. But I can see the Managed folder in /Applications/Hollow Knight.app/Contents/Resources/Data/Managed.

### Expected Behaviour

Open scarab

### Actual Behaviour

It crashes

### Logs

[ModInstaller.log](https://github.com/fifty-six/Scarab/files/11948762/ModInstaller.log)

**Comment by fifty-six** [comment]
Sorry for the wait, the newest version should fix this if you can give that a try

**Comment by TextAdventurer12** [comment]
this issue is still present on latest patch for me

**Comment by fifty-six** [comment]
Could you provide logs after trying to select the folder with the latest patch? I've added some more info to the logs since last time to try and make it easier to troubleshoot.

**Comment by ravenclaw900** [comment]
I have the same issue. Where can I find logs to post?

**Comment by fifty-six** [comment]
It'd be at `~/.config/HKModInstaller`, you can navigate to this by hitting Cmd+Shift+G in Finder if you don't have hidden files on

**Comment by ravenclaw900** [comment]
This log looks pretty barebones, but here it is:

<details>
<summary>Log file</summary>

```
2023-09-11 13:59:20.613 -05:00 [INF] Launching...
2023-09-11 13:59:21.837 -05:00 [INF] Initializing to normal mode (.cctor)
2023-09-11 13:59:23.613 -05:00 [INF] Checking if up to date...
2023-09-11 13:59:23.616 -05:00 [INF] Current version of installer is 2.1.0.0
2023-09-11 13:59:26.808 -05:00 [INF] Loading settings.
2023-09-11 13:59:26.908 -05:00 [INF] Unable to detect installation path for settings, selecting manually.
2023-09-11 13:59:28.977 -05:00 [INF] Selecting path...
```
</details>

**Comment by ravenclaw900** [comment]
Here's something interesting: I got it working in an older version, and then once I upgraded to the latest version, everything seems to be working.

**Comment by fifty-six** [comment]
Oh, what version was it?

**Comment by xxoo** [comment]
endless loop...

https://github.com/fifty-six/Scarab/assets/1268383/6362b4e9-324b-4b75-b35e-83e01cbb5afa

macos 13.5.2
Scarab 2.1.0
hollow knight 1.5.78.11833
