### ISSUE TITLE
Scarab No Longer Automatically Enables Dependencies

### ISSUE THREAD

**Issue by ethanskipsey** [fifty-six/Scarab#173]
### Scarab Version

v1.33.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Open Scarab and attempt to enable an installed mod with a number of dependencies that are not enabled.

### Expected Behaviour

The dependencies for the mod to be enabled automatically.

### Actual Behaviour

The switch moved to the 'On' position but turned grey rather than blue. Additionally the ability to enable any other mods was lost and the dependencies for that mod were not enabled. However, the mod can still be enabled by closing and reopening Scarab then enabling each dependency individually before enabling the mod in question.

### Logs

None

**Comment by fifty-six** [comment]
I completely forgot to respond to this one, I'll make sure to address it for the next release.

**Comment by fifty-six** [comment]
Could I get a list of what mods were enabled/disabled and what specifically you were enabling/disabling?

**Comment by fifty-six** [comment]
Ah I repro'd it, fixed it locally.
