### ISSUE TITLE
Invalid Hollow Knight Path issue

### ISSUE THREAD

**Issue by Ncarauj012** [fifty-six/Scarab#175]
### Scarab Version

v1.14.0.0

### Hollow Knight Version

most recent

### Steps to Reproduce

idk

### Expected Behaviour

I keep selecting the folder "Hollow Knight", inside of which is the "hollow_knight_Data" that scarab asks for, and selecting either of them ends in the same message saying that its invalid and prompts me to try again.

I am running linux mint's most recent version.

### Actual Behaviour

"Invalid Hollow Knight Path!
Select the folder containing hollow_knight_Data or Hollow Knight_Data."

### Logs

idk

**Comment by MysticalMT** [comment]
Same issue with original and pirated Hollow knight

**Comment by fifty-six** [comment]
Could you run `tree` on the folder from the terminal and post the output by any chance? In `hollow_knight_Data` is there a `Managed` folder containing `Assembly-CSharp.dll` and `UnityEngine.dll`? For the original issue poster, did you mean 1.14? The latest is v1.33

**Comment by grunixx** [comment]
my friend that is trying to play is having the same issue, his hollow knight is from gamepass but is the same problem
the scarab doenst find the path

**Comment by BlueRedShark** [comment]
> Could you run `tree` on the folder from the terminal and post the output by any chance? In `hollow_knight_Data` is there a `Managed` folder containing `Assembly-CSharp.dll` and `UnityEngine.dll`? For the original issue poster, did you mean 1.14? The latest is v1.33

I've got the same issue and I just want to clarify, what does running tree on the folder from the terminal mean, as in what does running tree mean?

**Comment by Ncarauj012** [comment]
> Could you run `tree` on the folder from the terminal and post the output by any chance? In `hollow_knight_Data` is there a `Managed` folder containing `Assembly-CSharp.dll` and `UnityEngine.dll`? For the original issue poster, did you mean 1.14? The latest is v1.33

okay so first of all, yes there is a folder named [Managed] with both files (Assembly-CSharp.dll and UnityEngine.dll), 

i'm using the most recent version i downloaded the day i posted the issue.

and what command is "tree"? i'm pretty sure i dont have this command... should i install an application for this?

**Comment by le-birb** [comment]
I've been having the same issue with the path selection - my Manged folder is there and in the right place, etc. I have discovered that version 1.31 works perfectly fine for me (I was unable to test 1.32 due what I believe is the text box crashing issue), so while a fix is being worked on, backdating a bit might help.

**Comment by fifty-six** [comment]
I just released v1.34, if any of you could try that - it should fix this issue, hopefully.

**Comment by eldruz** [comment]
v1.34 works fine, seems the issue is fixed for me

**Comment by fifty-six** [comment]
Alright, if anyone else has the issue feel free to lmk and I'll re-open this.
