### ISSUE TITLE
1 Scarab not finding Hollow knight path, 2 an exception occurring when trying to install mods, 3 and Hollow Knight opening to black screen when Scarab is installed.

### ISSUE THREAD

**Issue by BlueRedShark** [fifty-six/Scarab#176]
### Scarab Version

v1.33

### Hollow Knight Version

v1.5.80.11835

### Steps to Reproduce

Just Install Scarab, 1 try to change path, 2 try to install any mod, 3 open HK with Scarab downloaded.

### Expected Behaviour

Everything to work.

### Actual Behaviour

1 
<img width="435" alt="Screenshot 2023-07-08 123733" src="https://github.com/fifty-six/Scarab/assets/126373228/d267065d-2d3f-4bfc-8f9d-c0c827f28a43">
2
<img width="420" alt="Screenshot 2023-07-08 123703" src="https://github.com/fifty-six/Scarab/assets/126373228/6d12f11a-1b05-40e9-bfa0-e8ea12e0912b">
3 HK just has a black screen.

The reason why I have all 3 issues here is because I do not know if they are connected or not. I will close the other 2 issues that I put up so that all my problems will be collected here.

### Logs

2 [ModInstaller.log](https://github.com/fifty-six/Scarab/files/11987300/ModInstaller.log)

**Comment by fifty-six** [comment]
Whenever you get the chance, could you try v1.34, it should fix the path issues at least.

**Comment by BlueRedShark** [comment]
> Whenever you get the chance, could you try v1.34, it should fix the path issues at least.

It does not work, I still have all the same problems. I do have a theory on what's going on. That is, when installing Scarab, something in the code destroys the code for the game. I think this because, I opened the broken HK after installing Scarab, uninstalled Scarab while it is still open. (The error of not finding the correct path only shows up when I try to change path and then it says it cannot find the installation, so when I first open Scarab it appears fine) I re install Scarab with HK still open and instead of being able to do stuff, it brings me straight to the cannot find path error. So I believe that something in the Scarab code destroys the path for HK and so it can't find HK and HK also opens to a never ending black screen. Maybe I have a different problem to the other guy so hopefully 1.34 works for him but otherwise, it does not work for me. But Idk, I might be completely wrong.

**Comment by fifty-six** [comment]
Do you have the Xbox Gamepass version? The typical hollow knight version isn't 1.5.80, it's 1.5.78 - which is probably what would lead to a black screen

**Comment by BlueRedShark** [comment]
> Do you have the Xbox Gamepass version? The typical hollow knight version isn't 1.5.80, it's 1.5.78 - which is probably what would lead to a black screen

Yes, I do have the Xbox Gamepass version and I just checked now and it is 1.5.80

**Comment by BlueRedShark** [comment]
> Do you have the Xbox Gamepass version? The typical hollow knight version isn't 1.5.80, it's 1.5.78 - which is probably what would lead to a black screen

I forgot to add this but Scarab used to work for me and now it doesn't.

**Comment by fifty-six** [comment]
Ah, could you try resetting the path again? It can't find the modded Assembly-CSharp atm so it's dying, if you verify your game/whatever the Gamepass equivalent is and then change paths so it's at a "fresh slate" it should in theory work from there.

**Comment by emeldar** [comment]
@BlueRedShark I was running into this issue as well. Deleting my `%APPDATA%/HKModInstaller` folder fixed it for me.

**Comment by BlueRedShark** [comment]
> Ah, could you try resetting the path again? It can't find the modded Assembly-CSharp atm so it's dying, if you verify your game/whatever the Gamepass equivalent is and then change paths so it's at a "fresh slate" it should in theory work from there.

Yeah that apears to have worked, thanks
