### ISSUE TITLE
Application hangs attempting to install/update certain mods

### ISSUE THREAD

**Issue by MShrieken** [fifty-six/Scarab#178]
### Scarab Version

v1.34.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

1. Launch Scarab via .exe. 
2. Attempt to install Randomizer 4. 
3. Wait until frustrated, 30+ minutes.

### Expected Behaviour

After a short delay, the progress bar should stop revolving and fill from left to right, before install is completed.

### Actual Behaviour

The progress bar continually sends the 'waiting' signal, a short bar flying across the length of the window without being anchored to either side.

### Logs

None

**Comment by MShrieken** [comment]
Noticed this when attempting to install or update anything dependent on Randomizer4. Uninstalling the mod works correctly, but subsequent attempts to reinstall still prompt the above issue.

**Comment by fifty-six** [comment]
Did you check for the existence of logs? There should be some given the application launched at all.

**Comment by MShrieken** [comment]
I did, but couldn't find any 'HKModInstaller' folder in the suggested spots
of the issue form. Is there somewhere else they might be?

**Comment by fifty-six** [comment]
Nah, on windows the only location is just `%appdata%/HKModInstaller`, could I see a picture of your `%appdata%` folder maybe?

**Comment by PinkPlasma6083** [comment]
i'm having this same issue when trying to update the vocalized mod

**Comment by fifty-six** [comment]
Could you also give your logs? How long did you wait regarding the vocalized mod also? It's *huge* so it generally takes a bit longer than other mods, so some people have thought it was paused when it was still working.

**Comment by MShrieken** [comment]
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/12095437/ModInstaller.log)
found logs from another attempt just now

**Comment by arrowmahn** [comment]
having the same issue. looked in my logs and it says this at the very end:
https://github.com/homothetyhk/RandomizerMod/
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #17383282)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #22231815)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #65868610)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #55946580)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model

here is the full .log file:
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/12096824/ModInstaller.log)

**Comment by MShrieken** [comment]
Managed to figure a workaround, it seems to be hanging up on something to do with mod dependencies. Uninstalling then reinstalling all the mod's listed dependencies allowed me to download Randomizer 4, and from there, other mods dependent on Rando4.

**Comment by fifty-six** [comment]
Should be fixed now
