### ISSUE TITLE
Trying to turn on the mods, it's not happening.

### ISSUE THREAD

**Issue by Figggggg** [fifty-six/Scarab#179]
### Scarab Version

v1.34.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Switch installed inactive mod's activation tumbler to "on".

### Expected Behaviour

When I click the switch, after a second or so it turns blue, and the mod becomes active.

### Actual Behaviour

When I click the switch of inactive mod to "on", it immediately becomes grey and all of the other switches become inactive. Waited for a long period of time, nothing changed. Mods which were turned on before the scarab launch are turning on and off just fine.

### Logs

ㅤ

**Comment by Figggggg** [comment]
Little update here: the roundabout is reinstallation of all mods you have, so using this for now, but it doesn't really solve a problem.

**Comment by fifty-six** [comment]
Could you tell me all the mods you have installed? I couldn't repro this locally - but I imagine it's just a certain configuration. Sorry for taking a while to respond.

**Comment by Figggggg** [comment]
> Could you tell me all the mods you have installed? I couldn't repro this locally - but I imagine it's just a certain configuration. Sorry for taking a while to respond.

Sure. Benchwarp, BenchWarpFix, Carefree Grimm, ChangeHud, CharmPreset, CompassAlwaysOn, ConnectionMetadataInjector, Convenient Path of Pain, Custom Knight, CustomKnightPlus, DebugMod, Discord Rich Presence, Enemy HP Bar, Graphic Options, HKMirror, InfiniteNotches, ItemChanger, MenuChanger, MultiWorldLib, Osmi, PathOfPureVessel, QoL, Randomizer 4, Randomizer Core, RandoPlus, Satchel, SFCore, Vasi. 

And now for the issue: only PoPV, Vasi, QoL and Satchel were active, while others were just downloaded. And when I tried to turn on one of the downloaded (but not active) mods, they all turned grey and I couldn't do anything.

**Comment by paul0728** [comment]
i have the same problem

**Comment by fifty-six** [comment]
Should be fixed now, feel free to re-open if it isn't
