### ISSUE TITLE
Custom knight not responding with the game.

### ISSUE THREAD

**Issue by Alnez1953** [fifty-six/Scarab#18]
It appears to be running in the top left corner when it launches but it doesn't display in the mod menu for some reason. It was working just fine but when I relaunched the game it stopped recognizing custom knight as a mod. 

The pathing's correct the extra custom skins are where they need to be, I reinstalled scarab and the game to see if it'll work but that didn't fix the issue. Hk is not recognizing Custom Knight as a mod for some reason.

**Comment by fifty-six** [comment]
If the mod installed fine then the issue would be better suited for something like #modding-help within the discord. I'd check that the subfolder is in the Mods folder and the dll is in it though.

**Comment by Alnez1953** [comment]
Where can I find the discord?

**Comment by fifty-six** [comment]
discord.gg/hollowknight

**Comment by Alnez1953** [comment]
Thank you
