### ISSUE TITLE
Installer says HK is open when it isn't

### ISSUE THREAD

**Issue by Roselily2006** [fifty-six/Scarab#180]
### Scarab Version

v1.14

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Try to install a mod I guess

### Expected Behaviour

For the mod to be installed

### Actual Behaviour

A window popped up stating that Hollow Knight was open, even though it wasn't. The exe for HK was not present in Task Manager, either. Choosing to "close" HK gave me an error log. Choosing not to "close" it gave me an error pop up while trying to install the mod.

### Logs

[ModInstaller_Error_23-07-23 21-49-31.log](https://github.com/fifty-six/Scarab/files/12141296/ModInstaller_Error_23-07-23.21-49-31.log)

**Comment by fifty-six** [comment]
Sorry for taking forever - could I see logs for the choosing not to close option?

**Comment by Roselily2006** [comment]
It's alright! I may be able to get you the log, but in the time taken to respond, I have found that simply hitting x on the warning window lets the mod install as normal.

**Comment by fifty-six** [comment]
Oh lmao, that's good. I'll try and add some better error handling regardless.
