### ISSUE TITLE
App Freezes When Installing/Enabling Mods Without Their Dependencies

### ISSUE THREAD

**Issue by GamerFreddie** [fifty-six/Scarab#183]
### Scarab Version

v1.34.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Install/enable a mod without having all of its dependencies installed/enabled.
Examples:
- Trying to enable the mod "AdditionalMaps" without enabling "SFCore".
- Trying to install "RainbowEggs" without "Randomizer 4" already installed.

### Expected Behaviour

Feedback from the app (Pop-up or something of the sort) saying "This mod requires the following mod: [Dependecy]"
OR
Both the selected app and its dependencies being downloaded and/or enabled.

### Actual Behaviour

Sometimes the app acts like it is trying to install the mod (or, in the case of enabling, it freezes all the other enable switches as if it is processing something), and remains stuck in that "waiting" mode indefinetely.

NOTE: Before writing this report, I simply worked around this issue by manually installing the dependencies first. After I was able to do that and successfully launched the game with the mods, I came here to report the bug. However, as of writing this, I cannot replicate the bug, I don't know if there was something else at play that fixed itself after I was able to get around the issue or something, but figured I'd report it anyway, in case anyone else has been having this issue.

### Logs

[ModInstaller.log](https://github.com/fifty-six/Scarab/files/12504800/ModInstaller.log)

**Comment by gameo7** [comment]
Same thing happens when trying to install randomizer/randomapmod. Everything just grays out and I can't click on anything else. I'm guessing you just need to do it in a specific order?
