### ISSUE TITLE
[bug] Scarab doesn't launch on NixOS

### ISSUE THREAD

**Issue by TheBearodactyl** [fifty-six/Scarab#185]
### Scarab Version

v2.1.00

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Extract scarab from `linux.zip` to a directory named `scarab`
`cd` into `scarab`
execute Scarab with `$ ./Scarab`

### Expected Behaviour

I expected it to initialize after confirming the path to the Hollow Knight directory

### Actual Behaviour

fish: Job 1, './Scarab' terminated by signal SIGSEGV (Address boundary error)

### Logs

no logs were generated.
It just doesn't work.

**Comment by TheBearodactyl** [comment]
by the way, the reason I specified NixOS is because it works just fine on Arch and Gentoo

**Comment by fifty-six** [comment]
No logs were generated as in the log file is empty/doesn't exist or as in it doesn't output to stdout?

**Comment by TheBearodactyl** [comment]
> No logs were generated as in the log file is empty/doesn't exist or as in it doesn't output to stdout?

@fifty-six as in it doesn't even create the `~/.config/HKModInstaller` folder

**Comment by fifty-six** [comment]
Would you be open to trying a framework dependent version? You'd just need the .net6 runtime

**Comment by TheBearodactyl** [comment]
> Would you be open to trying a framework dependent version? You'd just need the .net6 runtime

sure

**Comment by fifty-six** [comment]
[This](https://we.tl/t-Y4pNv2614U) should work if you have net6 installed, sorry for the WeTransfer link, even with 7z it only went down to like 33mb and you need <=25 for github

**Comment by TheBearodactyl** [comment]
thanks :D 
By the way, you can upload separate files from it in chunks of less than 25MB to the same repo and it'll let you have it uploaded lol
