### ISSUE TITLE
Linux: Unable to select hollow knight path when hollow knight is saved on different hard drive

### ISSUE THREAD

**Issue by Will-J-Gale** [fifty-six/Scarab#186]
### Scarab Version

v2.1.0.0

### Hollow Knight Version

v1.6.1.3

### Steps to Reproduce

1. Install hollow knight onto a different hard drive.
2. Run Scarab
3. A popup appears saying something like "Cannot find installation of hollow knight"
4. It brings a popup allowing you to select the installation location.
5. Find the hollow knight installation
6. The bug: You cannot actually select a folder, you can only select files. Selecting the folder only opens it in the select window, it does not actually select it as the installation path. You can select a file, and doing so just gives an error saying it's not the hollow knight path.

I moved hollow knight back to the main hard drive using Steam's move function (/home/<USER>/.steam/debian-installation/steamapps/common/HollowKnight) and Scarab found the installation immediatly.

The issue just seems to be not being able to select folders when manually selecting the hollow knight installation folder

### Expected Behaviour

You should be able to select a folder, but it seems only files can be selected

### Actual Behaviour

Selecting the correct folder only opens the contents of the folder, it does not actually select the folder.

### Logs
[ModInstaller-20230911.log](https://github.com/fifty-six/Scarab/files/12570978/ModInstaller-20230911.log)

### OS
Ubuntu 20.04

**Comment by fifty-six** [comment]
If the application launched, there should be logs - are you sure the folder wasn't created?

**Comment by Will-J-Gale** [comment]
Yes I managed to find the logs, I've updated my initial comment with a link to the logs

**Comment by fifty-six** [comment]
What does the selection menu look like for you? It should look like this
![image](https://github.com/fifty-six/Scarab/assets/10470872/6c774e8b-5b3a-4141-b52d-17dd7d16dc47)

**Comment by Will-J-Gale** [comment]
![image](https://github.com/fifty-six/Scarab/assets/22546479/906814ba-4788-4219-8efb-34db9f1f3896)

Mine does not have the `select` button, only `open`. Clicking open on the Hollow Knight folder doesn't select it, it just opens the folder to show it's contents. There doesn't seem to be a way to actually select a path manually.

For reference I'm using Ubuntu 20.04.

**Comment by fifty-six** [comment]
Believe I've found the issue - https://github.com/AvaloniaUI/Avalonia/issues/10320, so I'm working on some stuff to work around it for now.

**Comment by GhostDog98** [comment]
Note: You can do a workaround for this by creating a symbolic link to the folder into your root directory :)
`ln /path/to/Hollow\ Knight ~/Hollow\ Knight`
And then selecting that
