### ISSUE TITLE
Scarab has a malware file?

### ISSUE THREAD

**Issue by SoteresX** [fifty-six/Scarab#189]
### Scarab Version

v2.1.0.0

### Hollow Knight Version

v1.5

### Steps to Reproduce

Just open the Scarab file

### Expected Behaviour

The program to launch

### Actual Behaviour

Antivirus detected a malware file on Scarab making it unable to launch.

### Logs

None

**Comment by fifty-six** [comment]
This is just a false positive from your anti-virus, there's usually a menu where you can add exclusions to the list.
