### ISSUE TITLE
No valid suffix with Managed folder

### ISSUE THREAD

**Issue by RawToast225** [fifty-six/Scarab#190]
### Scarab Version

2.1.0.0

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

Fresh install of Hollow Knight on second disk 
- mounted in my /Run directory

Run Scarab

Asked to select correct directory

### Expected Behaviour

It accepts my Data folder and moves on

### Actual Behaviour

Infinite loop of not having the right "valid suffix with Managed folder" and selecting the same folder

### Logs

[ModInstaller-20230917.log](https://github.com/fifty-six/Scarab/files/12644945/ModInstaller-20230917.log)

**Comment by RawToast225** [comment]
turns out i'm very dumb and it's actually supposed to be the one containing the Data folder, not the Data folder itself. It's clear, i just can't read i guess

**Comment by fifty-six** [comment]
Happens, I'll probably try and improve the UI for this though, it's kinda terrible rn
