### ISSUE TITLE
Immediate Crash when opening Scarab+

### ISSUE THREAD

**Issue by someone10394** [fifty-six/Scarab#191]
### Scarab Version

v2.3.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

When I opened scarab+ it needed an update, so i updated it but it was stuck even that it was done, i then went to scarab and it had the "Hollow Knight's saved path is invalid. Please select a path again" Error, but after i clicked OK it immediatly crashed, i tried to ignore the update but it still didnt work and i cant update it now

### Expected Behaviour

I thought when the update was done i would have a better experience

### Actual Behaviour

it crashed after clicking OK while on the error

### Logs

[ModInstaller_Error_23-09-23 11-04-12.log](https://github.com/fifty-six/Scarab/files/12706150/ModInstaller_Error_23-09-23.11-04-12.log)
[ModInstaller_Error_23-09-23 11-07-10.log](https://github.com/fifty-six/Scarab/files/12706151/ModInstaller_Error_23-09-23.11-07-10.log)

**Comment by someone10394** [comment]
i should also say that i cant do anything with it and now im stuck with modded Hollow Knight

**Comment by fifty-six** [comment]
The `_Error` logs are a "Scarab+ (Lumafly now)" thing - and 2.3 isn't a Scarab version either. If you want to try Scarab, then download the newest one (v2.1), and then the new errors/output are in Modinstaller2023xxxx.log
