### ISSUE TITLE
windows 7 suport

### ISSUE THREAD

**Issue by lsskofc** [fifty-six/Scarab#195]
### Scarab Version

N/A

### Hollow Knight Version

v1.5.68.1.11808

### Steps to Reproduce

nao abre=(

### Expected Behaviour

eu ia botar skin

### Actual Behaviour

a

### Logs

a

**Comment by fifty-six** [comment]
Aside from [Windows 7 not being officially supported by Avalonia](https://github.com/AvaloniaUI/Avalonia/wiki/Runtime-Requirements), this issue has no info attached, so unless you have logs or otherwise actionable information, I can't really help.
