### ISSUE TITLE
Showing Active Mods

### ISSUE THREAD

**Issue by 1993Pianist** [fifty-six/Scarab#196]
### Scarab Version

v2.3.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Please add an option to the mod settings to enable and disable UI while the game is running, because I don't like seeing it while playing the game. Thank you

### Expected Behaviour

...

### Actual Behaviour

...

### Logs

...

**Comment by fifty-six** [comment]
You can install the "Hide Mod List" mod, though this is out of scope for the app anyways.

**Comment by 1993Pianist** [comment]
Unfortunately, this mod that you mentioned does not work properly, also the fast travel mod, which is one of my favorites, has several annoying bugs and its developer does not react..

**Comment by fifty-six** [comment]
I mean, that's not really an issue regarding the installer - so the only real thing to do about that is just fix it yourself honestly. Regarding the hiding the mod which hides the list, note that you have to go to options -> mods -> hide mod list, and then set the option to hide it, as it doesn't default to hiding it.
