### ISSUE TITLE
it loads then stops

### ISSUE THREAD

**Issue by sleepyboy01** [fifty-six/Scarab#200]
### Scarab Version

2.4.0.0

### Hollow Knight Version

Idk most recent?

### Steps to Reproduce

download it then open the scarab file and it loads then closes

### Expected Behaviour

IDK

### Actual Behaviour

IDK

### Logs

idk

**Comment by fifty-six** [comment]
Is this your first time using Scarab? Can you check for logs in `%appdata%\HKModInstaller`?

**Comment by sleepyboy01** [comment]
yes, first time and where do I find that?

**Comment by fifty-six** [comment]
You can paste it in the explorer top bar or if you hit Windows+R and paste `%appdata%\HKModInstaller` it should open it, if not then `explorer.exe %appdata%\HKModInstaller` should.

**Comment by sleepyboy01** [comment]
> You can paste it in the explorer top bar or if you hit Windows+R and paste `%appdata%\HKModInstaller` it should open it, if not then `explorer.exe %appdata%\HKModInstaller` should.

yea I just looked and is scarab supposed to be in the file? or should it be moved there?

**Comment by SesterSir** [comment]
[ModInstaller-20231116.log](https://github.com/fifty-six/Scarab/files/13374087/ModInstaller-20231116.log)
Here's the log file I have, same problem. First time using, flashes open then closes.

**Comment by sleepyboy01** [comment]
> [ModInstaller-20231116.log](https://github.com/fifty-six/Scarab/files/13374087/ModInstaller-20231116.log) Here's the log file I have, same problem. First time using, flashes open then closes.

am I supposed to download it and replace my file? sorry I don't know what I am doing
