### ISSUE TITLE
Scarab keeps closing on me!

### ISSUE THREAD

**Issue by Aster-Disaster** [fifty-six/Scarab#201]
### Scarab Version

v2.4.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Download Scarab on Windows
Struggle to figure out how to open Scarab and get frustrated when it keeps closing.
Realize it's not your fault.

### Expected Behaviour

It opens and i can play Hollow Knight Randomizer

### Actual Behaviour

It'll open for a second, load, then close itself.

### Logs

None

**Comment by fifty-six** [comment]
Are you sure there aren't any logs - have you checked for the existence of the folder? Also, is this your first time using it - or is this after updating from a previous version?

**Comment by fifty-six** [comment]
Should be fixed in 3c72552, which is in the newest release!
