### ISSUE TITLE
does not have access to the folder

### ISSUE THREAD

**Issue by davinchombm02xd** [fifty-six/Scarab#202]
### Scarab Version

2.5.0.0

### Hollow Knight Version

1.4.2.4

### Steps to Reproduce

when i try to install a mod appears me this error 
![image](https://github.com/fifty-six/Scarab/assets/150490012/721fe294-6937-4364-8f05-1bbcc0467e8b)

### Expected Behaviour

can install a mod

### Actual Behaviour

appeared me this error

### Logs

![image](https://github.com/fifty-six/Scarab/assets/150490012/6aef1423-7d7e-4927-9a21-cc944800bdd8)

**Comment by fifty-six** [comment]
1424 isn't a supported game version - did you buy the game?
