### ISSUE TITLE
Team Cherry splash screen not appearing once the modding API is on.

### ISSUE THREAD

**Issue by demperor-music** [fifty-six/Scarab#203]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Enable modding API, then start the game

### Expected Behaviour

The game starts with the Team Cherry splash screen

### Actual Behaviour

There's no splash screen and you're dropped into the main menu with a generic loading screen.
Not really a big issue to be honest, but I would rather have the TC splash screen than a loading screen

### Logs

[ModInstaller-20231123.log](https://github.com/fifty-six/Scarab/files/13453278/ModInstaller-20231123.log)

**Comment by fifty-six** [comment]
The loading screen is unrelated, that's a side-effect of having a mod which needs to preload resources enabled. The API just skips the logo entirely as a bit of a speed-up. Regardless, this isn't a bug nor is it related to the installer.
