### ISSUE TITLE
Doesn't work on GOG/Windows?

### ISSUE THREAD

**Issue by Ponitek** [fifty-six/Scarab#21]
Mods don't load in the game. Scarab created hollow_knight_Data and everything inside looks fine, but doesn't work. I don't get any error or anything. I tried merging the folders, but it didn't help. (At first I had an issue with assembly_CSharp.dll not appearing, but my friend send me one, and it works for him).

**Comment by fifty-six** [comment]
Created hollow_knight_Data? It should be using the `Hollow Knight_Data` folder that's already there, is that not the case?

**Comment by Ponitek** [comment]
No, it's creating a new folder hollow_knight_Data, which only has mods in it.

**Comment by fifty-six** [comment]
Does [this](https://cdn.discordapp.com/attachments/440483082366091264/926284139760615455/publish.zip) work for you?

**Comment by Ponitek** [comment]
It's working! Thank you so much!
