### ISSUE TITLE
Scarab does not start

### ISSUE THREAD

**Issue by Igrosi** [fifty-six/Scarab#211]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Answer my question, please, and help me

### Expected Behaviour

When I try to open Scarab, it simply won't open.

### Actual Behaviour

I wanted to install mods, but I ran into the problem that Scarab simply doesn't even start, which is why I had a doubt - Does Scarab work on windows 7?

### Logs

None

**Comment by fifty-six** [comment]
I believe Avalonia - the framework this uses, doesn't support Windows 7, sorry.

**Comment by Igrosi** [comment]
> Я полагаю, что Avalonia - фреймворк, который этот использует, не поддерживает Windows 7, извините.

Oh, it's sad(
