### ISSUE TITLE
Scarab not opening

### ISSUE THREAD

**Issue by BobaNChikn** [fifty-six/Scarab#212]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Install Scarab
Extract files
Open Scarab.exe (error 1)
Open Scarab.exe from the downloaded .zip folder (error 2)

### Expected Behaviour

For Scarab to open.

### Actual Behaviour

The .exe file disappeared and scarab didn't open.
I also attempted to open the application from the .zip file. the file did not disappear from the folder, but still did not open and instead gave me this popup:
![Scarab error mesage](https://github.com/fifty-six/Scarab/assets/164288119/ffe9285c-86f8-44fc-83d9-ac5c0cba51e2)

### Logs

Launching...
Launching...
Launching...
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
Scarab Error: 0 : System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 23
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 20
   at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 19
   at Avalonia.AppBuilder.SetupUnsafe() in /_/src/Avalonia.Controls/AppBuilder.cs:line 302
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 291
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 199
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 219
   at Scarab.Program.Main(String[] args)
    DateTime=2023-06-14T02:23:10.9554482Z
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #2522270)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #22700437)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #2977343)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #26796095)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Scarab Error: 0 : System.MissingMethodException: Attempted to access a missing method.
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider , MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at Scarab.ViewModels.MainWindowViewModel.CheckUpToDate() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 196
   at Scarab.ViewModels.MainWindowViewModel.Impl() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 55
   at Scarab.ViewModels.MainWindowViewModel.<.ctor>b__10_0() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 287
    DateTime=2023-06-30T05:02:11.6628354Z
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Scarab Error: 0 : System.MissingMethodException: Attempted to access a missing method.
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider , MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at Scarab.ViewModels.MainWindowViewModel.CheckUpToDate() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 196
   at Scarab.ViewModels.MainWindowViewModel.Impl() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 55
   at Scarab.ViewModels.MainWindowViewModel.<.ctor>b__10_0() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 287
    DateTime=2023-06-30T05:02:45.2505160Z
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Scarab Error: 0 : System.MissingMethodException: Attempted to access a missing method.
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider , MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at Scarab.ViewModels.MainWindowViewModel.CheckUpToDate() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 196
   at Scarab.ViewModels.MainWindowViewModel.Impl() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 55
   at Scarab.ViewModels.MainWindowViewModel.<.ctor>b__10_0() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 287
    DateTime=2023-06-30T05:02:53.9508223Z
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Scarab Error: 0 : System.MissingMethodException: Attempted to access a missing method.
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider , MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at Scarab.ViewModels.MainWindowViewModel.CheckUpToDate() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 196
   at Scarab.ViewModels.MainWindowViewModel.Impl() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 55
   at Scarab.ViewModels.MainWindowViewModel.<.ctor>b__10_0() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 287
    DateTime=2023-06-30T19:24:05.1214392Z
Launching...
Scarab Error: 0 : System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 23
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 20
   at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 19
   at Avalonia.AppBuilder.SetupUnsafe() in /_/src/Avalonia.Controls/AppBuilder.cs:line 302
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 291
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 199
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 219
   at Scarab.Program.Main(String[] args)
    DateTime=2023-06-30T19:24:13.1813999Z
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #20059788)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #46320367)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #14230125)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #60962261)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #44799155)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #539219)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #4852978)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #43676810)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #51099441)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #57241785)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #45414023)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #6073027)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #6006001)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #54054017)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #16724107)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #16299242)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #55373821)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #28602343)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #56094502)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #35088474)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #57344383)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #46337402)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #14383437)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #62342073)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #47289184)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #22949479)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #5218725)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #46968531)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #66520277)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #61811587)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #19433374)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #40682639)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #61443550)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #16121045)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #10871681)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #30736267)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #38001140)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #6465948)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #58193536)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #53979776)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #5074772)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #45672950)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #8403368)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #34175649)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #39145392)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #16764208)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #16660147)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #8314412)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #7720849)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #2378778)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #21409010)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #2484416)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #22359750)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #67020028)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #66309348)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
https://github.com/PrashantMohta/HollowKnight.CustomKnight/
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #11090802)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #32708358)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #25939770)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #32131343)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #36611159)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #61064975)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #12713868)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #7057909)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #63521186)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #34819765)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #17401978)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #22400077)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #274103)
[Binding]Error in binding to 'Avalonia.Animation.AnimatorKeyFrame'.'Value': 'Null value in expression '{empty}' at '$parent[ProgressBar, 0]'.'(AnimatorKeyFrame #2466929)
Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #30265903)
Loading settings.
Settings path is invalid, forcing re-selection.
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #56592155)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #39567352)
[Binding]Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.'(KeyBinding #20561848)

**Comment by fifty-six** [comment]
You fully extracted the zip first? The error is that it's missing the dlls which come in the zip with it. If WinRAR is being weird or something the default archive tool should work fine. I'd also note if you move the exe you have to move the dlls too. Running directly from the zip isn't supported

**Comment by BobaNChikn** [comment]
> You fully extracted the zip first? The error is that it's missing the dlls which come in the zip with it. If WinRAR is being weird or something the default archive tool should work fine. I'd also note if you move the exe you have to move the dlls too. Running directly from the zip isn't supported

I did extract every file in the .zip folder, so that shouldn't be the issue.

**Comment by fifty-six** [comment]
What log file is that actually? It's several launches and the last one is just trying to get you to reselect the folder for your game

**Comment by BobaNChikn** [comment]
> What log file is that actually? It's several launches and the last one is just trying to get you to reselect the folder for your game

It was the only log from that day

**Comment by BobaNChikn** [comment]
I believe I found what the issue was. another user of this computer set up an antivirus software that was falsely flagging the application as malware. I am not sure how to stop this from happening but I asked the user that installed the software to help me figure it out.

**Comment by fifty-six** [comment]
Ah ok, thanks for the update!
