### ISSUE TITLE
Antivirus detected a Troyan

### ISSUE THREAD

**Issue by Snt1049** [fifty-six/Scarab#213]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

latest one

### Steps to Reproduce

while I was executing the scarab to install it McAfee detected a virus and immediately sent it to destroy.

### Expected Behaviour

To work correctly, having no issues while installing it.

### Actual Behaviour

As I said the antivirus sent the installer to destroy and because of fear i decided not to install it.

### Logs

None

**Comment by fifty-six** [comment]
You just have to set it as exempted in whatever settings McAfee has, some antiviruses do this to software sometimes.
