### ISSUE TITLE
hollow knight closes for no reason

### ISSUE THREAD

**Issue by marsha1719** [fifty-six/Scarab#214]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

v1.5.68

### Steps to Reproduce

I install any mod and when I open hollow knight it suddenly closes without even showing the home screen
I have uninstalled hollow knight and scarab but I don't have any solution

### Expected Behaviour

I expected hollow knight to open without any problem but it is quite the opposite

### Actual Behaviour

I can't find what the problem is why hollow knight closes

### Logs

![image](https://github.com/fifty-six/Scarab/assets/166466665/bf8c3af8-6858-420d-ad01-499b8cd90d3c)

**Comment by marsha1719** [comment]
please someone help me with this

**Comment by fifty-six** [comment]
v1.5.68 isn't supported, only the latest version.
