### ISSUE TITLE
bug: PS4 controller stops detecting by the game

### ISSUE THREAD

**Issue by kibin** [fifty-six/Scarab#22]
intel macmini 2018, macOS 11.6.2
HK 1.5.78.11833 installed through Steam (latest version as of today).
I had problem with steam with using controller overlay, so I turned it off, and fresh install of the game detects my controller automatically with no problems. But when I’m installing scarab (v1.8.0.0), it stops detecting it.

How did I test it:
Installed Scarab, installed mods, opened HK, it didn’t detect controller as usual
turned mods off, same situation
deleted mods, no luck
deleted scarab, freshly installed the game (since I couldn’t find, how to uninstall it)
now it works

is there a workaround or is this a bug?

**Comment by fifty-six** [comment]
This is an API issue which sometimes pops up. It's usually fine now that we've started using the mac/linux binaries for their own builds but it still happens occasionally. Not entirely sure why still as we don't really touch the input system. As far as the bug actually goes the steam controller overlay sometimes works out, other times people use stuff like joy2key. In the case that neither work, you can always revert to vanilla by disabling the api. If that doesn't work, you can also verify your game files in steam. I would leave the issue open or something but there's not really much to do as far as the installer goes.

**Comment by kibin** [comment]
> This is an API issue which sometimes pops up. It's usually fine now that we've started using the mac/linux binaries for their own builds but it still happens occasionally. Not entirely sure why still as we don't really touch the input system. As far as the bug actually goes the steam controller overlay sometimes works out, other times people use stuff like joy2key. In the case that neither work, you can always revert to vanilla by disabling the api. If that doesn't work, you can also verify your game files in steam. I would leave the issue open or something but there's not really much to do as far as the installer goes.

it’s interesting that there is a workaround for this, as discussed in [hk speedrunning discord](https://discord.com/channels/772964112908156938/822831192150638643/927236584804323379)

**Comment by kibin** [comment]
it worked. maybe it’s something to add to readme for users like me? Enjoy 2 (joy2key alternative for macos) also worked

**Comment by Highonkola** [comment]
> it worked. maybe it’s something to add to readme for users like me? Enjoy 2 (joy2key alternative for macos) also worked

Hey dude, the link that leads to the discord doesnt work for me, do you mind sharing what is in it since I am havong the same problem that while scarab is active my controller doesnt work

**Comment by kibin** [comment]
> Hey dude, the link that leads to the discord doesnt work for me, do you mind sharing what is in it since I am havong the same problem that while scarab is active my controller doesnt work

I’m not a dude, nor the dude, but hey anyway. are you registered on hk discord?

TL: DR

The first way is to use Enjoy2 to map your controller to keyboard keys.

the workaround on the discord:
> Here's a build of 1578 modding API that should work for Unix systems (MacOS | Linux):
https://cdn.discordapp.com/attachments/880463689176731648/917836286608441374/OutputFinal.zip
To install it, just open up the part in that download that should be a folder with like 10 files (including AssemblyCsharp), and copy and paste those into your Managed Folder inside the hollow knight install.

**Comment by Highonkola** [comment]
I am very sorry! I use dude for either male or female or everthing else, but I can understand that that is not the nicest way to talk to someone. I didn't want to offend you.

thank you very much for the link and the tip with enjoy2
