### ISSUE TITLE
bug or what

### ISSUE THREAD

**Issue by loli-hub** [fifty-six/Scarab#227]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

версия 1.5.78.11833

### Steps to Reproduce

scarab say select a valid path

### Expected Behaviour

scarab say select a valid path

### Actual Behaviour

scarab say select a valid path

### Logs

[HKInstallerSettings.json](https://github.com/user-attachments/files/16725498/HKInstallerSettings.json)

**Comment by fifty-six** [comment]
what?
