### ISSUE TITLE
feature request: uninstaller or instruction on how to uninstall

### ISSUE THREAD

**Issue by kibin** [fifty-six/Scarab#23]
intel macmini 2018, macOS 11.6.2
HK 1.5.78.11833 installed through Steam (latest version as of today).

I found out that there is no instruction on how to uninstall Scarab (1.8.0.0), so I think it’s important to have one to troubleshoot cases like in [previous issue](https://github.com/fifty-six/Scarab/issues/22).

**Comment by fifty-six** [comment]
Disable the API and then delete the .app if you feel like it.

**Comment by kibin** [comment]
thanks, but how do you disable the api?

**Comment by kibin** [comment]
oh nvm, found it
