### ISSUE TITLE
Scarab closes in 1-2 minutes after trying to Install API

### ISSUE THREAD

**Issue by Fcmns** [fifty-six/Scarab#230]
### Scarab Version

v2.5.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Re-enter the path to game directory
Restart Scarab
Click on the "Install API" button

### Expected Behaviour

Everything working properly

### Actual Behaviour

Scarab closes after 1-2 minutes after clicking on the button

### Logs

[ModInstaller-20240923.log](https://github.com/user-attachments/files/17096327/ModInstaller-20240923.log)

**Comment by fifty-six** [comment]
So, it shouldn't be crashing for this, but what's happening is it's failing to download stuff (timing out after ~100s), and then dying from there. If you go to https://github.com/hk-modding/api and go to releases can you download it fine?
