### ISSUE TITLE
Нет файла Scarab.exe

### ISSUE THREAD

**Issue by MOBatov** [fifty-six/Scarab#233]
### Scarab Version

2.5.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Установил исходный архив и распаковал

### Expected Behaviour

Наличие Scarab.exe

### Actual Behaviour

Отсутствие Scarab.exe

### Logs

![1](https://github.com/user-attachments/assets/ba383b94-83c7-4aac-a28c-9b783811febb)

**Comment by fifty-six** [comment]
You gotta download the exe from the [releases](https://github.com/fifty-six/Scarab/releases/tag/v2.5.0.0), not the repository zip.
