### ISSUE TITLE
Message prompt too small to display while message

### ISSUE THREAD

**Issue by Nicholas-Steel** [fifty-six/Scarab#24]
![image](https://user-images.githubusercontent.com/11567846/148682040-5e68c90f-cd6b-4887-a181-e9063c83e2dc.png)

Also there's no indication it can be scrolled to show the rest as the Scroll Down arrow isn't visible.

**Comment by fifty-six** [comment]
Was fixed in 8946d2fd894ebf0e1807d37e718faac6653fada5
