### ISSUE TITLE
Background get's messed up on "low" and "medium" blur quality.

### ISSUE THREAD

**Issue by FatCodingPig** [fifty-six/Scarab#25]
When you put on "low" or "medium" blur quality, the background gets messed up. Even without any mods on. I'm on an old mac and on high blur quality my computer lags. Here's an image from my game on low quality:
![Screenshot 2022-01-15 at 11 55 32](https://user-images.githubusercontent.com/89932660/149621418-4a0adf07-4f44-49af-ae6a-83ef6c6c5b44.png)

**Comment by SFGrenade** [comment]
do you have a comparison with vanilla hollow knight?

**Comment by fifty-six** [comment]
Additionally, does this happen with the API disabled?

**Comment by FatCodingPig** [comment]
Yes I do have a comparison with vanilla. On vanilla low, medium and high work just fine.

**Comment by FatCodingPig** [comment]
Scarab doesn't give me an option to update or toggle API
![Screenshot 2022-01-16 at 9 41 57](https://user-images.githubusercontent.com/89932660/149651643-4a61120a-9739-4af8-8b48-542e87621880.png)
.

**Comment by FatCodingPig** [comment]
Menu also gets messed up btw

**Comment by fifty-six** [comment]
Verify your game integrity and then show the main menu before/after installing mods.

**Comment by FatCodingPig** [comment]
What do you mean by verify your game integrity?

**Comment by fifty-six** [comment]
https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

**Comment by FatCodingPig** [comment]
After changing path, again to Hollow Knight, the menu works on low, medium and high and the seeing second layer on borders: top and bottom is fixed only one problem remains. Second layer remains invisible.

**Comment by FatCodingPig** [comment]
Verifying game integrity doesn't change anything.

**Comment by FatCodingPig** [comment]
Idk man Ill just download my worlds and ill reinstall Hollow Knight.
