### ISSUE TITLE
Not able disable API

### ISSUE THREAD

**Issue by Highonkola** [fifty-six/Scarab#26]
On mac there is still an issue where you cant use your controller when the Mod is enabled. In the last version it was still possible to disable the API so the controller works again. WIth the new update the disable API button is gone. Is there another way to disable the API?

**Comment by fifty-six** [comment]
[You can verify your game integrity in steam](https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB), though if you try to install a mod in theory it should let you disable the api if you can't for some reason. I believe the controller issue *should* also be fixed now for modded anyways as the API build got updated to better support macOS. If installing a mod doesn't work you can also hit change path and re-select the hollow knight app which should reset what mods the installer tracks.

**Comment by Highonkola** [comment]
yeah I seem to have just bricked my version of hollow knight on this mac. I cant even get the modloader to open anymore but I would guess that is a very niche problem of my version so I will close the issue
