### ISSUE TITLE
api-ms-win-core-winrt-l1-1-0.dll Missing on windows 7 after update

### ISSUE THREAD

**Issue by HeWhoThreadsLightly** [fifty-six/Scarab#29]
![image](https://user-images.githubusercontent.com/39104806/151702311-ccd04186-1591-4a2b-ba9d-8993cb4c1747.png)
Scarab was unable to launch after i updated to v1.9.0.0 from an older version.

![image](https://user-images.githubusercontent.com/39104806/151702394-c659fe12-8123-4709-8233-ebb0ba5a8e7e.png)
I was unable to find version information for the old install but here is the image if you recognize the files.

Found a download for api-ms-win-core-winrt-l1-1-0.dll here: https://windll.com/dll/microsoft-corporation/api-ms-win-core-winrt-l1-1-0#method-1
Inspected it with windows system essentials and found no suspicious string constants. 
[apiStrings.txt](https://github.com/fifty-six/Scarab/files/7966022/apiStrings.txt)

I could launch Scarab after adding the dll to my scarab install folder.

**Comment by fifty-six** [comment]
It's a thing with Windows 7 not being supported for .NET 6 single-file publishing. You can get the dependencies [here](https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net60#additional-deps). It's an annoying change but I don't want to go back to .NET 5.
