### ISSUE TITLE
[Suggestion] Readmes

### ISSUE THREAD

**Issue by SFGrenade** [fifty-six/Scarab#33]
from a discord server.
![grafik](https://user-images.githubusercontent.com/25555417/152139486-ec01a837-0556-4366-9728-3e9029b02f9d.png)

**Comment by fifty-six** [comment]
i am not downloading the entire mod to show someone a readme

**Comment by fifty-six** [comment]
Someone can put a README link tag in modlinks or something and then I can look at it but until then I'm not changing that.

**Comment by DwarfWoot** [comment]
IMO, old Mod Installer was flawed in needing to download the entire mod to get the readme. Is it reasonable to add an optional <readme>url.here</readme> tag to modlinks, and then add a 📝icon next to each mod that has it linked on Scarab (or just put a "ReadMe" link before the Dependency list in the Mod Description section)? 

I think it's reasonable to have users load the readme's in their browser. _Most_ mods are on GH anyway, and those that aren't can potentially link to pastebin or something if the dev wants to add a readme.

**Comment by TheMulhima** [comment]
> Someone can put a README link tag in modlinks or something and then I can look at it but until then I'm not changing that.

wouldn't that break previous versions of scarab?
