### ISSUE TITLE
(Suggestion) Gray out "Enabled?" text along with its check box

### ISSUE THREAD

**Issue by Geroyuni** [fifty-six/Scarab#36]
It is not very visually clear that "Enabled?" is not clickable, because although the check box is greyed out, it isn't a very prominent shape and is hard to notice. Greying out the text should make it easier for users' eyes to notice that and concentrate on "Installed?" and other parts of the UI more quickly.

![comparison](https://user-images.githubusercontent.com/6061850/152668201-39a3aef0-331c-42d4-870e-b051a51881d2.png)

**Comment by fifty-six** [comment]
![installer with gray text](https://user-images.githubusercontent.com/10470872/152894893-f2b8e951-d15d-4f2d-ad7c-f1b0c8f72e26.png)
