### ISSUE TITLE
Scarab keep crashing my game

### ISSUE THREAD

**Issue by SkylarTheChristian** [fifty-six/Scarab#37]
So i got hollow knight (GOG ver.) and it works perfecty but everytime i path it to scarab it crashes. Even when i remove scarab's mods it doesnt work and i have to get a new hollow knight game. The crash is saying KERNELBASE.DLL VIOLEDED ACCESS or something like that and idk why.

**Comment by fifty-six** [comment]
What version do you have?

**Comment by SkylarTheChristian** [comment]
> What version do you have? Can I see the error logs? They're in your saves folder. Also, does it look like the Assembly-CSharp in the game's data/Managed folder has been replaced?

i have the latest one. If ur talking about Hk its 1.4.3.2

**Comment by SkylarTheChristian** [comment]
No i still see the Assembly-CSharp.dll i dont think it was replaced

**Comment by SkylarTheChristian** [comment]
where do i see the saves folder i cant find them

**Comment by fifty-six** [comment]
Did you pirate the game? 1.4.3.2 is multiple versions old and thus unsupported. Update your game through GOG or buy the game.

**Comment by SkylarTheChristian** [comment]
Ok thank you and yes it is a pirated version but I'll get it ->-
