### ISSUE TITLE
Nexus Mods added?

### ISSUE THREAD

**Issue by FormSans** [fifty-six/Scarab#40]
I was trying to search 'Easier Mode - Cheap Charms' that is on Nexus mods on this (amazing) program, but I can't find it. Is there a place I can suggest it or just allow mods from Nexus to be added?

**Comment by fifty-six** [comment]
Nexus mods are generally done by patching the assembly directly, as opposed to the mods on the installer which are modules loaded by the API, with the API being the only direct patch to the assembly. Direct patches don't really go together so all the nexus mods of that won't be compatible with the other mods on the installer. In addition, the installer is coded around the idea of every mod being an API mod as well as taking from a source of them, so it would be a pain to get nexus mods on it. If you want reduced charm costs, `Easy Mode` is on the installer, and has configurable options - one of which decreases charm costs by 1.
