### ISSUE TITLE
Scarab on Linux

### ISSUE THREAD

**Issue by sociallyakwardfrog** [fifty-six/Scarab#43]
So i've tried to downloading the linux zip file multiple times and extracting it, and i don't know if i'm doing something wrong or if the file is corrupted because when trying to run it. A prompt saying "No programs for shared library files" pops up

**Comment by darklink64** [comment]
Putting some elements for those trying to figure it out, as I experienced the same issues: 

Runing ./Scarab from the terminal is working. 

Upon starting however, it doesn't find my game path. I entered the following : 
`/home/<user>/.steam/debian-installation/steamapps/common/Hollow Knight`

I had the following error "unable to fetch modlinks", restarting my system got rid of it and I can now run Scarab (tried on Ubuntu 20.04).
