### ISSUE TITLE
SHA of neither API nor Mods are checked

### ISSUE THREAD

**Issue by SFGrenade** [fifty-six/Scarab#44]
https://github.com/fifty-six/Scarab/blob/c48b4a962898f48ca7aa631e5e6c13ff206d44f1/Scarab/Services/Installer.cs#L132

https://github.com/fifty-six/Scarab/blob/c48b4a962898f48ca7aa631e5e6c13ff206d44f1/Scarab/Services/Installer.cs#L245

**Comment by omppye** [comment]
This is kinda serious

**Comment by fifty-six** [comment]
I've been meaning to get around to that

**Comment by fifty-six** [comment]
d144bf1377cff405fa77007f10e605c29ed0b082, said 7 instead of #44 in the desc.
