### ISSUE TITLE
Custom Knight downloading error.

### ISSUE THREAD

**Issue by osu4GBRAM** [fifty-six/Scarab#45]
Custom Knight worked on 1.9.0.0, but now it says it has an invalid hash. I tried redownloading but no luck.

**Comment by osu4GBRAM** [comment]
Exact Error: "The download hash for Custom Knight (6546EF2C92511145B3D3CAC427A8D7845C28657FEF7121401A9185FB042205B0) didn't match the given signature (db429735c36e7915373f4661b759e8a263520cbc0634aed69d1d63fdca0418cb). It is either corrupt or the entry is incorrect."

**Comment by fifty-six** [comment]
That is an issue for the custom knight dev, the hash check failing is what it should be doing considering it has the wrong hash.

**Comment by osu4GBRAM** [comment]
Lol sorry
