### ISSUE TITLE
HK for Mac, Sony PS4 controller no longer works after installing Scarab.

### ISSUE THREAD

**Issue by mkldrekka** [fifty-six/Scarab#46]
I purchased HK yesterday and played it for a couple hours, using my official Sony PS4 controller (not a third-party controller).

I am running HK v1.5.78.11833 and installed Scarab v1.9.0.0 on a MacBook Pro running Big Sur. 

I installed Scarab yesterday and when I tried to start the game back up, I could no longer use the controller on HK and could not access the modding menus at all... they are visible on screen in game, but I couldn't click on anything.  I could use F1 to hide / show the menus could not interact with them.

My PS4 controller still worked on Steam, but not in the HK program.

I uninstalled HK and reinstalled it without Scarab and my controller worked fine in game again.

Anyone know how to get it working while modding API is working?

Thanks, great interface and super simple to use!

**Comment by mkldrekka** [comment]
I am going to try v1.10.0.0 today and do some other trouble shooting and post an update.  If you have any thoughts in the meantime, hit me!  ; )

**Comment by osu4GBRAM** [comment]
I think you've installed "debug mod", because if you press F1, a menu shows. You might not be able to interact with the options because you're screen resolution is weird. If you want to fullscreen, don't do Alt+Enter. Instead go into settings -> video -> fullscreen. I have no idea why your PS4 controller isn't working, you may need to go (in steam) to the little settings icon -> proporties -> controller and try troubleshooting there.

**Comment by osu4GBRAM** [comment]
Also you can only interact with the debug meu using your mouse.

**Comment by mkldrekka** [comment]
Thanks for the advice, I will try this today.  Yeah, I tried using debug mod.  I am basically trying to use a mod to help me get past bosses with invincibility (I love exploring the game, but hate bosses), then turn off mods.  If you know of a mod besides "debug mod" to do this, let me know!  ; )

**Comment by mkldrekka** [comment]
I tried many different settings and controller configs to both Steam and HK, but couldn't get my PS4 controller to work in HK while using mod API... strange.  Ultimately, I just enabled "debug mod", used my keyboard to get through the boss fight, then used "local files --> verify integrity of game files" to remove the API and continue playing with my PS4 controller... very strange.

**Comment by fifty-six** [comment]
This is an API thing and I'm not entirely sure why it still happens given that we use the base dlls now.

**Comment by mkldrekka** [comment]
In the end, I decided to just go wit ha wired connection for my PS4 and I was able to get Scarab and the mods working... but only with the keyboard.  When the API is enabled, I can use the keyboard, but not the controller... when I disable to API, the controller starts working again.

Any ideas on how to get around that so I can use mods AND my controller?

**Comment by fifty-six** [comment]
Are you using steam's controller thing? I've heard that can make it work/not work

**Comment by mkldrekka** [comment]
I tried a variety of combos of enabling the API, then opening HK and disabling the API and disabling the steam controller, then quitting and restarting... can't remember which combo/order worked, but eventually it started working!  Thanks for the suggestion!
