### ISSUE TITLE
Blank scarab

### ISSUE THREAD

**Issue by MegaLP** [fifty-six/Scarab#47]
Ok, so I just get an empty screen and an error in the logs.

![grafik](https://user-images.githubusercontent.com/56975441/156032709-9080fb54-bd52-4b68-882b-fe93518b0855.png)

`Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Settings doesn't exist. Creating it at detected path ValidPath { Root = D:\\Games\\SteamLibrary\\steamapps\\steamapps\steamapps\common\Hollow Knight, Suffix = hollow_knight_Data/Managed }.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24412946)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #18389930)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #31291646)
[Binding] Error in binding to 'Avalonia.Controls.Image'.'IsVisible': 'Could not find a matching property accessor for 'Icon' on 'MessageBox.Avalonia.ViewModels.MsBoxStandardViewModel'' (Image #58577354)
Fetching links
Launching...
`

**Comment by fifty-six** [comment]
Seems like [Avalonia#5543 maybe](https://github.com/AvaloniaUI/Avalonia/issues/5543), does [this version](https://files.catbox.moe/uleliz.zip) work for you?

**Comment by Shadudev** [comment]
Got the same issues, still with the version linked above.
```text
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Current version of installer is 1.9.0.0
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #16246551)
Installer out of date! Version 1.9.0.0 with latest 1.10.0.0!
Loading settings.
ConfigPath: File @ C:\Users\Shadu\AppData\Roaming\HKModInstaller\HKInstallerSettings.json exists.
Fetching links
```

**Comment by osu4GBRAM** [comment]
Well, if my reading skills are good enough, I think it can't bind to 'Avalonia.Input.KeyBinding' A.K.A I think there's something wrong with your installation.

**Comment by osu4GBRAM** [comment]
And Something's wrong with OpenGL

**Comment by p1nus** [comment]
I'm the author of the closed #41, sorry for the lack of update, I rarely use GitHub. Anyways, here's the zip file as requested
[HKModInstaller.zip](https://github.com/fifty-six/Scarab/files/8190457/HKModInstaller.zip)

**Comment by p1nus** [comment]
> I'm the author of the closed #41, sorry for the lack of update, I rarely use GitHub. Anyways, here's the zip file as requested [HKModInstaller.zip](https://github.com/fifty-six/Scarab/files/8190457/HKModInstaller.zip)

I've also tried some versions of Scarab, yet none works

**Comment by fifty-six** [comment]
Could you give the logs with the newer version? The logs were broken in earlier versions and the newer ones give a lot more information. I'll see if I can get another version with more logging later when I get the chance so I can better see what the issue is, not sure if something happens after fetching links or if it's just OpenGL dying

**Comment by p1nus** [comment]
> Could you give the logs with the newer version? The logs were broken in earlier versions and the newer ones give a lot more information. I'll see if I can get another version with more logging later when I get the chance so I can better see what the issue is, not sure if something happens after fetching links or if it's just OpenGL dying

Sure!
This time, it's different, it can now detects installation path although after that the application is still a blank canvas. 
[HKModInstaller.zip](https://github.com/fifty-six/Scarab/files/8192250/HKModInstaller.zip)

**Comment by fifty-six** [comment]
Is [this](https://files.catbox.moe/gy8q8v.zip) any different? I added a bit of logging but more importantly it isn't built as a single-file thing which might help with the whole OpenGL bit

**Comment by fifty-six** [comment]
Are either/both of these links accessible to you? [github](https://raw.githubusercontent.com/hk-modding/modlinks/main/ModLinks.xml), [jsdelivr](https://cdn.jsdelivr.net/gh/hk-modding/modlinks@latest/ModLinks.xml). It looks like it's hanging on fetching the links which would happen if github loads too slowly (>5s) or is unavailable and then jsdelivr is unavailable.

**Comment by p1nus** [comment]
> 

Although I don't really know what's going on, I think it does. It loads pretty much instantly. Here's some screenshots:
![image](https://user-images.githubusercontent.com/97348477/157657012-bfaba493-e7b0-4238-9342-a86f49c93d12.png)
![image](https://user-images.githubusercontent.com/97348477/157657042-90ed6d53-282a-4de5-8b0c-491007b1a008.png)

**Comment by fifty-six** [comment]
Does [this](https://files.catbox.moe/ront6x.zip) do anything different? I added a bit more regarding the actual link requests. Sorry if it took a bit, was busy

**Comment by p1nus** [comment]
> Does [this](https://files.catbox.moe/ront6x.zip) do anything different? I added a bit more regarding the actual link requests. Sorry if it took a bit, was busy

Sorry for the late response. There's a tiny difference, that being the addition of an error screen like this:
![image](https://user-images.githubusercontent.com/97348477/161705223-378af963-d687-4ef8-b745-c4fa1b12f1e1.png)

**Comment by p1nus** [comment]
I'm not sure but could it be related to this god awful bug where even though I have access to the Internet but Windows still shows that no connection globe? 
![image](https://user-images.githubusercontent.com/97348477/161705935-1d6bf029-a4e0-4408-b340-6b07fee382cc.png)

**Comment by fifty-six** [comment]
Are you using a proxy or VPN by any chance?

**Comment by astorioth** [comment]
Hi, I'm having the same blank scarab+unable to fetch modlinks timeout error, but on the linux version. I'm not using VPNs or proxys.

**Comment by fifty-six** [comment]
Does `curl https://raw.githubusercontent.com/hk-modding/modlinks/main/ModLinks.xml` work for you?

**Comment by THEDAN320** [comment]
hi, what version of windows do you have? in one of the topics of avalonia there was an explanation of this error. this is due to the fact that GetDpiForMonitor was added only in windows 8.1

**Comment by IgLocoXD** [comment]
`D:\Games\SteamLibrary\steamapps\steamapps\steamapps\common\Hollow Knight, Suffix = hollow_knight_Data/Managed`
If you read the path, in the "hollow_knight_Data/Managed", The slash need to be inverted like this; \ Windows uses inverted slashes, Linux & MacOS uses the normal (/) ones.

Go to %appdata\HKModInstaller, and then edit the settings with this; `D:\Games\SteamLibrary\steamapps\steamapps\steamapps\common\Hollow Knight, Suffix = hollow_knight_Data\Managed`

Idk if this is gonna have a major fix, but really this help me with the SAME error with Linux (that even the settings file was not created because Scarab doesn't detect the HK Folder in Linux ver)

**Comment by hltl** [comment]
I just met the same issue, and it works when I'm using a VPN.

**Comment by fifty-six** [comment]
[This might resolve some of the issues](https://files.catbox.moe/axphx1.zip), lmk if this works/doesn't work for anyone. Changed both the OpenGL thing and made TaskCanceledExceptions log more and more carefully checked that it's an actual timeout.

**Comment by Pippatis** [comment]
Hello, I'm having the same issue, both with the official build of Scarab as well as the test build you linked. I tried uninstalling/reinstalling Hollow Knight, deleting my mods folders and the ModInstaller folder before running the program just so it could start with a blank slate, same results both ways. Here are the logs I got for both builds.
[ModInstaller - official build.log](https://github.com/fifty-six/Scarab/files/9173991/ModInstaller.-.official.build.log)
[03d372bf-234f-48c1-82db-e8173f492cecModInstaller - test build.log](https://github.com/fifty-six/Scarab/files/9173992/03d372bf-234f-48c1-82db-e8173f492cecModInstaller.-.test.build.log) 
I hope this helps! Let me know if there's anything else you need.

**Comment by PapaiJarda** [comment]
> Hello, I'm having the same issue, both with the official build of Scarab as well as the test build you linked. I also tried uninstalling/reinstalling Hollow Knight, deleting my mods folders and the ModInstaller folder before running the program just so it could start with a blank slate, same results both ways. ... I hope this helps! Let me know if there's anything else you need.
Same here.

**Comment by fifty-six** [comment]
lmk if the newest release doesn't fix it and I'll reopen the issue

**Comment by p1nus** [comment]
it works now lesss gooo
