### ISSUE TITLE
cant open

### ISSUE THREAD

**Issue by Tectoplasme** [fifty-six/Scarab#54]
when I try to open it, it does nothing....that's all. Some times it says I don't have a "core" thing and seems to block the usage of it because of that.
Can you help?

**Comment by fifty-six** [comment]
OS? Version?

**Comment by Tectoplasme** [comment]
> OS? Version? What _exactly_ does it say?

Its the windows one.. and now the error doesn't appear anymore but it still wont open the list of mods.

**Comment by Tectoplasme** [comment]
I got help from some one else so its alright now
