### ISSUE TITLE
I'm a little lost

### ISSUE THREAD

**Issue by Impartious** [fifty-six/Scarab#56]
I've been using an older version of Scarab for about a month now, and it got caught up in some space clearing and was deleted. In this new version it is able to download fine, But I'm having trouble running the app. In the previous versions there was a .exe file to run but I can't find one anymore. Am I missing a step?

**Comment by SFGrenade** [comment]
you probably downloaded the wrong zip.
you go to <https://github.com/fifty-six/Scarab/releases/latest> and download `windows.zip`, which does contain a `.exe` file.

**Comment by Impartious** [comment]
Ahh yep there it is.  I was just missing something. Thank you so much!
