### ISSUE TITLE
Scarab QoL Enhancements

### ISSUE THREAD

**Issue by Hotklou2404** [fifty-six/Scarab#62]
1. I think it could be useful if, in the description of each mod, you could click a button to go to the repository where that mod's files are hosted, if applicable. I sometimes struggle to find these repositories through Google Search. Likewise, a link to this repository could also be nice.
2. Perhaps there could be two tabs in the description of each mod, one for a description of what the mod does and the second for a changelog of the mod's updates. This changelog could be set to automatically populate with text provided by the developer of that mod in some file or another (same with the description of the mod, actually), so as to reduce the amount of work you have to do.

**Comment by fifty-six** [comment]
Both of these would require changing the actual modlinks format, though if that gets done I can definitely add these

**Comment by SFGrenade** [comment]
for the first, i could make the necessary changes to modlinks. though that may take a bit as i probably will make it mandatory, as optional it would lead to 90% of mods not having that information and it wouldn't get added and new mods would also lack that information, as people adding to modlinks copy the necessary block from another mod that likely misses that info.

**Comment by fifty-six** [comment]
Don't think the second thing would realistically happen as you'd need everyone to note down all their changes, so I'm just gonna close this. You can also see the changes between versions with the repository link using the commit history now.
