### ISSUE TITLE
I can't open Scarab

### ISSUE THREAD

**Issue by Asits61** [fifty-six/Scarab#63]
I can't open Scarab.exe .It doesn't gives me any error message or something. It just says "Launching..." in the log.

**Comment by fifty-six** [comment]
Are you on the latest version? What platform?

**Comment by Asits61** [comment]
I am on the latest game version and using windows 7

**Comment by fifty-six** [comment]
Avalonia isn't entirely supported on Windows 7 fwiw. What version of the *installer* are you using though

**Comment by Asits61** [comment]
1.11

**Comment by Asits61** [comment]
this is latest right?

**Comment by fifty-six** [comment]
yes

**Comment by fifty-six** [comment]
What log are you looking at exactly

**Comment by Asits61** [comment]
appdata-->HKModInstaller-->log   i think, i don't remember exactly i am at school right now

**Comment by Asits61** [comment]
i got home now and yep its in 
%appdata%\HKModInstaller\ModInstaller.log

**Comment by Asits61** [comment]
Can i use the old version (ModInstaller) instead?

**Comment by fifty-six** [comment]
No. Would appreciate it if you try a newer version, but the old app doesn't support newer HK mods.
