### ISSUE TITLE
No mod size limit

### ISSUE THREAD

**Issue by SFGrenade** [fifty-six/Scarab#65]
idk how much work it would be, but maybe it would be a good idea to, when download mods or the api, download them into a temporary file and checking the sha of that temporary file instead of doing so in RAM.
it could be faster and would eliminate the inherent download size limit that scarab has.

**Comment by fifty-six** [comment]
This would be slower because you'd be bound by the disk speed. It might be worth streaming into disk for stupid large mods but given that we know for the most part they're all zips it's going to be strictly slower to have to write and then read again.

**Comment by SFGrenade** [comment]
true, tho my only thought creating this was stupidly large mods

**Comment by fifty-six** [comment]
Might come back to this if someone starts doing dumb large mods, but for now not really concerned with it.
