### ISSUE TITLE
Handle case when the API is already installed

### ISSUE THREAD

**Issue by kikones34** [fifty-six/Scarab#67]
Scarab assumes the game is clean when opening it up for the first time, and it makes a backup of `Assembly-CSharp.dll` when installing the modding API. However, for those of us who were using the previous mod installer and already had that file patched, this backup is actually a modded backup. So when pressing "Disable API", the game is still modded.
That's quite confusing, maybe we could add a warning if the original file doesn't match the expected hash?

**Comment by fifty-six** [comment]
Was hoping mostly for this issue to just kinda resolve itself with time as it would involve some form of hard-coding the current version hash in again or reflectively opening the dll. I might add it in though considering it's still too common an issue even if it's fairly rare.

**Comment by kikones34** [comment]
At this point I think this is no longer an issue, closing.
