### ISSUE TITLE
Longer mod names are cut off by the new On/Off button

### ISSUE THREAD

**Issue by MurdoMaclachlan** [fifty-six/Scarab#70]
I love the new visual design - it's a lot more intuitive than before - however at the moment the positioning cuts off longer mod names. Some examples below:

![image](https://user-images.githubusercontent.com/47920497/168265303-c4628343-f8c9-4452-b66a-50d723e76d86.png)
![image](https://user-images.githubusercontent.com/47920497/168265314-d75ec642-8603-42d4-bbf5-927b4dfa7fcb.png)
![image](https://user-images.githubusercontent.com/47920497/168265354-181d8a37-91ce-4a83-9a7e-21c3382e6e52.png)

**Comment by SFGrenade** [comment]
it could be
https://github.com/fifty-six/Scarab/blob/41d762367243dc403e38751e4f492eb7918e4132/Scarab/Views/ModListView.xaml#L124
with the `MaxWidth="180"` doing that
