### ISSUE TITLE
Path not finding

### ISSUE THREAD

**Issue by ixtee** [fifty-six/Scarab#75]
selected the hollow knight data folder and it said it wasnt the right folder, even tho it tells me to select that folder

**Comment by fifty-six** [comment]
You're supposed to select the folder containing that folder.

**Comment by ixtee** [comment]
Thanks! But now when I try to install a mod I get an exception error

**Comment by fifty-six** [comment]
Create another issue with the logs from `%appdata/HKModInstaller/` (or whatever is appropriate for your OS if not Windows)
