### ISSUE TITLE
[Feature Request] Update all button

### ISSUE THREAD

**Issue by flibber-hk** [fifty-six/Scarab#77]
Because it's slightly more convenient than waiting for the last mod to update before updating the next one

**Comment by fifty-six** [comment]
You *should* be able to queue several at once already, if that isn't the case I'll look into that

**Comment by fifty-six** [comment]
Though this is still something I'd like to add at some point

**Comment by flibber-hk** [comment]
> You should be able to queue several at once already, if that isn't the case I'll look into that

Apologies for taking so long to get back to this - as far as I can tell, you can't queue several to update at once unless there's a dependency relation involved.

https://user-images.githubusercontent.com/76987839/183247363-14878cfc-df6e-4135-a0e4-0217365e339d.mp4

**Comment by pi314ever** [comment]
Is this on the timeline to be added anytime soon?

**Comment by fifty-six** [comment]
Yeah, it's already on master - I just haven't put out a release. I can do so rn
