### ISSUE TITLE
Unable to launch Scarab on OSX 12.4

### ISSUE THREAD

**Issue by dfcs** [fifty-six/Scarab#79]
Permissions are set correctly. Gave the app the correct chmod credentials. This is the only debug info I can get out of the app when launching from Terminal:

The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000009b9f20 {Error Domain=NSPOSIXErrorDomain Code=111 "Unknown error: 111" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by fifty-six** [comment]
Is there any log in `~/.config/HKModInstaller`? Or next to the executable or .app?

**Comment by digitalvagrancy** [comment]
Not working for me either - same OS, downloading and trying for the first time.
I can't see any log or information - simply doesn't do anything when opened.

Thanks for all your work on this.

**Comment by fifty-six** [comment]
Are you guys using the Intel Macs or the M1 or M2 ones?

**Comment by digitalvagrancy** [comment]
Great question: I'm using an M1 Max. That well could be it.

**Comment by fifty-six** [comment]
Is it running under Rosetta?

**Comment by digitalvagrancy** [comment]
I've tried running it with and without Rosetta, and doesn't do anything either time.

**Comment by fifty-six** [comment]
Does [this](https://files.catbox.moe/ri56ta.zip) work by any chance? You'll have to run it through the terminal and `chmod +x` like 

```bash
cd ~/Downloads/osx-arm64
chmod +x ./Scarab
./Scarab
```

but this should be built for arm64

**Comment by digitalvagrancy** [comment]
I'm happy to try, but I'm out of my depth running terminal commands.
I can open terminal, but can you give me a step by step of exactly what to type in?

**Comment by fifty-six** [comment]
Pretty much exactly what was in the code block. You extract the zip and it'll extract to something like `osx-arm64`, and if that's in your Downloads folder you'd type `cd ~/Downloads/osx-arm64`. Then you'll do `chmod +x ./Scarab` and `./Scarab`. If it extracts to like `osx-arm64` with a nested `osx-arm64` folder in it, you'd type `cd ~/Downloads/osx-arm64/osx-arm64` at the start instead.

**Comment by digitalvagrancy** [comment]
Okay, it all worked just as you said but... nothing I'm afraid.

**Comment by fifty-six** [comment]
Did it just end with no output or did it have any logs in the terminal? If you look at `~/.config/HKModInstaller` is there any log there? (You can go there by hitting Cmd+Shift+G)

**Comment by digitalvagrancy** [comment]
I think I'm doing something wrong as I don't really understand how to look up logs. I don't have anything called 'HKModInstaller' either, only an app called Scarab.
Is it possible I have missed a step?

**Comment by fifty-six** [comment]
Nah it just saves the settings to a folder named that because that's what it was originally named after. If you hit Command+Shift+G in Finder and use `~/.config` as the path there might be a folder there called `HKModInstaller` - if there is there would be logs with it.

**Comment by digitalvagrancy** [comment]
Ah I was trying to type it into terminal.
~/.config/HKModInstaller or ~/.config doesn't seem to go anywhere I'm afraid.

**Comment by fifty-six** [comment]
Sorry for the wait, not entirely sure where to go from here as I can't reproduce the issue.  When you used the terminal and ran it the terminal itself showed no output? There's usually something like 
```bash
$ ./yadayada
     # some message, especially if there's an error
$ 
```
Though it seems like from what you described there just isn't this time. Does getting the [.NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) do anything by any chance?

**Comment by dfcs** [comment]
Sorry for my absence. I was traveling for work. I managed to get it to work. The problem seems to be that there is no `./config` directory by default. So, when I tried to navigate to it, it wasn't there. I created the `./config` directory and launched the app again and it worked as-designed. Seems like that directory needs to be created or updated to something within the Scarab app package. Hope this helps.

**Comment by fifty-six** [comment]
./config? like in the same folder as the app? It should try for ~/.config. I'll try fixing that though thank you!

**Comment by dfcs** [comment]
No, it has to go in the ~/ directory.

**Comment by fifty-six** [comment]
@digitalvagrancy If you could try the new version and tell me if that works, that would be great! If it doesn't could you open another issue?

**Comment by digitalvagrancy** [comment]
Sorry I was moving house and only recently got internet again - just tried and it looks like it worked perfectly!
Well done everyone, thanks for all your hard work and expertise!
