### ISSUE TITLE
Hollow knight won't launch

### ISSUE THREAD

**Issue by KadinRR** [fifty-six/Scarab#82]
when I try launching Hollow Knight with Scarab mods installed, it'll open a popup window saying "Hollow Knight encountered an issue and must close".

it also made a crash file, I'll attach the error.log

[error.log](https://github.com/fifty-six/Scarab/files/8988321/error.log)

**Comment by fifty-six** [comment]
What mods did you install? Was your game already modded or anything before using the installer? If you hit disable api and then verify your game integrity under `Right click -> Properties -> Local Files -> Verify integrity of game files...` it should fix itself

**Comment by KadinRR** [comment]
it wasn't modded, i'm using benchwarp, connectionmetadatainjector, itemchanger, magicUI, menuchanger, QoL, randomizable levers, randomizer 4, randomizer map s, randomizercore, randomizersettings randomizer, and vasi

i'll try the verify integrity of game files thing

**Comment by fifty-six** [comment]
If you uninstall all the mods but leave the modding api enabled is it still black?

**Comment by KadinRR** [comment]
it just immediately crashes

**Comment by fifty-six** [comment]
With the modding API disabled, what version of the game do you have?

**Comment by KadinRR** [comment]
1.4.3.2

**Comment by fifty-six** [comment]
You need the latest version of the game, i.e. 1.5.78.11833, for the installer to work.

**Comment by KadinRR** [comment]
awesome, thank you!
