### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by Sakurenmochi** [fifty-six/Scarab#85]
I've installed and unzipped scarab, but now my game won't open.

**Comment by fifty-six** [comment]
What version of the game did you have? What version of Scarab are you using? What mods did you install?

**Comment by Sakurenmochi** [comment]
Latest versions of each, about 27 mods including their dependencies.

**Comment by fifty-six** [comment]
Misclicked, but what are the actual version numbers. This depends on platform/provider/making sure you're not on any betas or anything. What are said mods. When you say the game doesn't *open*, does it crash on open with the pop-up? Does it black screen? If you disable the modding api in the installer does it open again?

**Comment by Sakurenmochi** [comment]
I'm on Windows with game [v1.5.78.11833] and scarab v1.14.0.0
(https://steamcommunity.com/ogg/367520/announcements/detail/3066381328906585083)
![2022-07-05](https://user-images.githubusercontent.com/108649363/177276691-7fdee65f-d90a-4e32-bc2b-29821f34866e.png)
![2022-07-05 (1)](https://user-images.githubusercontent.com/108649363/177276735-6fcb28f8-3710-427b-a2b5-87f7c0ac6947.png)
![2022-07-05 (2)](https://user-images.githubusercontent.com/108649363/177276792-afd114f8-9056-430b-bb78-5c545a37ab16.png)
![2022-07-05 (3)](https://user-images.githubusercontent.com/108649363/177276805-99dc5da7-86b7-432a-9151-55e727aaeaeb.png)
![2022-07-05 (4)](https://user-images.githubusercontent.com/108649363/177276813-b20a7b5a-3932-4b8c-b159-29badfd19b7f.png)

**Comment by ewewmac** [comment]
Exact same thing is happening to me, tried reinstalling the game but that didn't change anything

**Comment by ewewmac** [comment]
Yes it would still crash, from what I noticed after starting the game up
and having scarab installed. It caused 2 files to be deleted or removed I’m
not sure. When it crashed, I ran a file check on steam to make sure all the
files were there. 2 files needed to be retrieved then the game would launch
properly without crashing, but the mods weren’t active even if the api was
enabled.

**Comment by fifty-six** [comment]
I assume you're also on 1.5.78-11833?

**Comment by Sakurenmochi** [comment]
I tried with the mods disabled and got this.

![2022-07-07](https://user-images.githubusercontent.com/108649363/177823405-b0f78ee9-9a31-43bc-a16d-d2f91f0d380e.png)

**Comment by ewewmac** [comment]
Did you download the game through steam?  If so you right click on the game
on your library in steam , go into properties, game files, then you should
have verify the files.

**Comment by Sakurenmochi** [comment]
Thanks, I got it working.
