### ISSUE TITLE
Cant download any mods

### ISSUE THREAD

**Issue by Senzei2** [fifty-six/Scarab#86]
Everytime i try to download a mod it says an exception occurred whili downloading ______
I am playing the voidheart version so i dont know if thats the problem

**Comment by fifty-six** [comment]
Please attach logs from %appdata%/HKModInstaller or near the exe, this report isn't enough to do anything as-is

**Comment by fifty-six** [comment]
Re-open with the new template if you don't mind and haven't gotten it to work, thanks.
