### ISSUE TITLE
CUstom Knight bug

### ISSUE THREAD

**Issue by Retr05124** [fifty-six/Scarab#87]
**Describe the bug**
When I try to install custom knight it says there was a exception in intalling or uninstalling the mod

**To Reproduce**
1. Go to 'Custom knight mod on windows (steam version)'
2. Click on 'Install on the mod'
3. Wait

**Expected behavior**
THe mod installing

**Screenshots**

**Versions**
 - HK: 1.4.3.2 / 1.5.7.8.11781 / ...
 - Scarab: v2.1.0.0

**Installed Mods (if applicable)**

**Logs**
- Modinstaller.log (if it exists - at %appdata%/HKModInstaller/ or ~/.config/HKModInstaller/
- Logs next to the .app/.exe/... if they exist  

If the game crashed and the issue is Scarab specific and not an issue for a particular mod:
NOTE: Do NOT report mod bugs here.
- ModLog.txt, Player.log in the HK Saves folder

**Additional context**

**Comment by fifty-six** [comment]
You didn't fill out the form, re-submit or edit and post something here with the entire thing filled because as-is this is unactionable
