### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by prpjzz** [fifty-six/Scarab#91]
### Scarab Version

v1.16.0.0

### Hollow Knight Version

v1.4.3.2

### Steps to Reproduce

Game automatically turns off after installing Mod in Scarab.

### Expected Behaviour

Game will open,

### Actual Behaviour

Game automatically shuts down, then creates a crash folder in %userprofile%\AppData\LocalLow\Team Cherry\Hollow Knight\Crashes\
[error.log](https://github.com/fifty-six/Scarab/files/9142432/error.log)

### Logs

None.

**Comment by prpjzz** [comment]
Let me ask you a little bit more: Can you add that feature to allow manual mod installation?
Thanks you.

**Comment by fifty-six** [comment]
No
