### ISSUE TITLE
An exception occurred while installing or uninstalling 

### ISSUE THREAD

**Issue by tekash7** [fifty-six/Scarab#92]
### Scarab Version

v1.16.0.0

### Hollow Knight Version

v5.80.11835.0

### Steps to Reproduce

open the scarab and select a mod for example the custom knight or satchel give it to install and at once the error pops up.

### Expected Behaviour

that the installation box was checked as well as the enabled box

### Actual Behaviour

I got the error an exception occurred while installing or uninstalling 

### Logs

https://github.com/fifty-six/Scarab/files/9157565/ModInstaller_Error_22-07-21.02-47-20.log

Since I don't know how to add files, here I put the link to download the file that leaves me when trying to install the mod

**Comment by fifty-six** [comment]
Could you try running it as Administrator?

**Comment by tekash7** [comment]
i just tried to open as administrator but i get the same error

**Comment by fifty-six** [comment]
Can you give me the logs for that one?

**Comment by fifty-six** [comment]
Actually, someone has told me there's a thing you have to do regarding the Microsoft Store, 
![image](https://user-images.githubusercontent.com/10470872/180285029-9c3c1463-6f77-4106-b881-a92b0678a559.png)
Does this end up working for you?

**Comment by tekash7** [comment]
yes that method worked for me thanks

**Comment by SlaysikGG** [comment]
hey

**Comment by SlaysikGG** [comment]
i have this problem too
if my scarab find the correct path
