### ISSUE TITLE
Windows version refusing to extract

### ISSUE THREAD

**Issue by SuperIronMan987** [fifty-six/Scarab#94]
### Scarab Version

v1.16.0.0

### Hollow Knight Version

not relevant (i dont think) but its v1.5.78.11833

### Steps to Reproduce

What i think happened is that i accidentally tried to run it before HK had fully installed, and now everything refuses to run or extract it

### Expected Behaviour

The folder should extract and be able to run the file

### Actual Behaviour

The folder does not extract (it extracted fine before the accidental running)

### Attempted Fixes

Re-downloading the zip, extracting using different methods (7zip & windows default extraction)

### Logs

None

**Comment by fifty-six** [comment]
wdym doesn't extract? What's the error? This sounds unrelated to the software itself, but you could try moving it to like your Documents folder and extracting it there.

**Comment by SuperIronMan987** [comment]
so i still dont understand whats happening, but if i move the zip i can extract it again, but i still have the issue of it refusing to run the exe
![image](https://user-images.githubusercontent.com/70151481/180841356-0ee4949b-8d64-4aa7-a216-ca140293ae95.png)
it gives me this error if i run the exe (my account is the computer admin account) and once i run it i can never extract it again in that folder

**Comment by fifty-six** [comment]
What happens if you run it as Administrator? (Right click -> Run as Administrator)?

**Comment by SuperIronMan987** [comment]
it gives the same error

**Comment by SuperIronMan987** [comment]
also the error it gives when failing to extract is that it 'Cannot open output file : Access is denied. : C:\Users\getfi\Videos\Captures\windows\Scarab.exe'

**Comment by fifty-six** [comment]
Also why are you extracting it again? Does this happen with other zips too? Just seems like an OS issue.

**Comment by SuperIronMan987** [comment]
It doesn't happen with other zips, and im extracting it again because the exe deletes itself once i get the error

**Comment by SuperIronMan987** [comment]
issue seems to be fixed
