### ISSUE TITLE
Scarab Aborting on Launch. (Arch Linux)

### ISSUE THREAD

**Issue by TheBoss313** [fifty-six/Scarab#95]
### Scarab Version

v1.16.0.0, v1.15.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Download `linux.zip` archive, extract, run Scarab.  
Neither double click, terminal, or `sudo` terminal work.
Nute, I am using [SteamOS](https://github.com/theVakhovskeIsTaken/holoiso) running on my PC.

### Expected Behaviour

Scarab opens and works.

### Actual Behaviour

Scarab window opens, a few seconds later it closes.

### Logs

[ModInstaller_Error_22-07-25 09-41-00.log](https://github.com/fifty-six/Scarab/files/9183540/ModInstaller_Error_22-07-25.09-41-00.log)
[ModInstaller_Error_22-07-25 09-41-31.log](https://github.com/fifty-six/Scarab/files/9183541/ModInstaller_Error_22-07-25.09-41-31.log)
[ModInstaller_Error_22-07-25 09-48-00.log](https://github.com/fifty-six/Scarab/files/9183542/ModInstaller_Error_22-07-25.09-48-00.log)
[ModInstaller_Error_22-07-25 13-19-29.log](https://github.com/fifty-six/Scarab/files/9183543/ModInstaller_Error_22-07-25.13-19-29.log)

**Comment by fifty-six** [comment]
Could I have the log in `~/.config/HKModInstaller`?

**Comment by TheBoss313** [comment]
[ModInstaller_Error_22-07-25 09-41-00.log](https://github.com/fifty-six/Scarab/files/9183595/ModInstaller_Error_22-07-25.09-41-00.log)
[ModInstaller_Error_22-07-25 09-41-31.log](https://github.com/fifty-six/Scarab/files/9183597/ModInstaller_Error_22-07-25.09-41-31.log)
[ModInstaller_Error_22-07-25 09-48-00.log](https://github.com/fifty-six/Scarab/files/9183598/ModInstaller_Error_22-07-25.09-48-00.log)
[ModInstaller_Error_22-07-25 09-50-19.log](https://github.com/fifty-six/Scarab/files/9183599/ModInstaller_Error_22-07-25.09-50-19.log)
[ModInstaller_Error_22-07-25 10-19-30.log](https://github.com/fifty-six/Scarab/files/9183600/ModInstaller_Error_22-07-25.10-19-30.log)
[ModInstaller.log](https://github.com/fifty-six/Scarab/files/9183601/ModInstaller.log)

**Comment by fifty-six** [comment]
Ah this is a known thing I think. Can you try installing `ttf-ms-fonts` from the AUR?

**Comment by TheBoss313** [comment]
It worked, thanks! I would recommend putting this somewhere like a "known bugs" page so that it's easier to fix.
