### ISSUE TITLE
scarab cant find hollow_knight_Data or exception occurred while installing or uninstalling 

### ISSUE THREAD

**Issue by SlaysikGG** [fifty-six/Scarab#96]
### Scarab Version

v1.16.0.0

### Hollow Knight Version

v1.5.7.8.183

### Steps to Reproduce

i download scarab and say path is invalid hollow_knight_data i dont have a license of hollow knight and i download from GoG pls help with this error

### Expected Behaviour

bugged scarab pls help

### Actual Behaviour

help me

### Logs

help
i just want to download custom knight

**Comment by SlaysikGG** [comment]
and i tried to download mods on 1.4.3.2 but i dont know what mod bundle im from russia and not so good in english

**Comment by fifty-six** [comment]
You gotta use current patch, not 1432. And you want to select the folder which has hollow_knight_Data in it, not the hollow_knight_Data folder itself. So usually you'd select the one that's just titled "Hollow Knight"

**Comment by SlaysikGG** [comment]
i select and hollow_knight_Data but scarab says invalid path
please select Hollow_Knight_Data or hollow_knight_Data

**Comment by fifty-six** [comment]
Does your data folder contain a folder called `Managed` in it and within that an `Assembly-CSharp.dll` and a `UnityEngine.dll`?

**Comment by SlaysikGG** [comment]
ye in managed i have assembly-csharp.dll and a UnityEngine.dll but while i select the path i cant see assembly and unityengine i cant select it

**Comment by SlaysikGG** [comment]
early i download mods and i dont have this problems
but now i cant understand what is this error

**Comment by SlaysikGG** [comment]
maybe im need to download hollow knight 1.5.7.8 183 from another not GoG?

**Comment by SlaysikGG** [comment]
but it too not works

**Comment by SlaysikGG** [comment]
i tried early do this
and scarab find the path
but while i want to download mods 
i dont remember what scarab say
and i just cant download mods

**Comment by SlaysikGG** [comment]
if you can fix it please

**Comment by SlaysikGG** [comment]
i tried new version of scarab 1.19.00
but invalid path i select hollow knight and hollow knight_Data

**Comment by SlaysikGG** [comment]
i cant understand
why its dont works now
but early i download 1.15.00 in winter and it works

**Comment by SlaysikGG** [comment]
thx for 1.19.00 i finally can download mods

**Comment by Nardeem** [comment]
> Does your data folder contain a folder called `Managed` in it and within that an `Assembly-CSharp.dll` and a `UnityEngine.dll`?

Hi I have the same issue but I don't have those two files, what do I do?
