### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Oofys-death-world** [fifty-six/Scarab#98]
### Scarab Version

1.17.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Open Scarab
Browse for a minute or less
Crash

### Expected Behaviour

No Crash?

### Actual Behaviour

Yes crash

### Logs

[ModInstaller_Error_22-07-27 11-44-39.log](https://github.com/fifty-six/Scarab/files/9194887/ModInstaller_Error_22-07-27.11-44-39.log)

**Comment by fifty-six** [comment]
Thanks for the error report, seems to be an Avalonia thing with Wgl. https://github.com/AvaloniaUI/Avalonia/issues/5562. Went back to not using that.
