### ISSUE TITLE
Disabled Mods Not Detected

### ISSUE THREAD

**Issue by dastrdly6585** [fifty-six/Scarab#99]
### Scarab Version

v1.17.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

Start up Scarab and disable one or more mods.  Close Scarab and then reopen Scarab.

### Expected Behaviour

Disabled mods show as installed but disabled under "All" and "Installed", but not "Enabled".  Disabled mods can be re-enabled by clicking the switch.

### Actual Behaviour

Mods that were previously disabled are not detected at all by Scarab and are removed from the list of installed mods.

### Logs

[2fb16ef6-4201-4c2a-9b94-6431cf01814dModInstaller.log](https://github.com/fifty-six/Scarab/files/9195156/2fb16ef6-4201-4c2a-9b94-6431cf01814dModInstaller.log)

**Comment by fifty-six** [comment]
Thanks for catching this

**Comment by fifty-six** [comment]
Oh yeah and to like re-show the disabled mods that are gone, I'd just delete them from Disabled and then re-install and re-disable.
